"""
Automation Review Agent
=======================
Senior SDET / Code Reviewer agent that reviews AI-generated automation
code for correctness, framework compliance, maintainability, and reliability
BEFORE the code is committed to the test suite.

This is distinct from ReviewAgent (which reviews test cases).
This agent reviews the GENERATED PYTHON CODE.

Responsibilities:
  - Verify correct use of framework components (POM, fixtures, XLUtils)
  - Check assertion quality and error handling
  - Detect hardcoded values (URLs, credentials, paths)
  - Verify Allure decorators are present and correct
  - Check for flaky patterns (time.sleep, unstable selectors)
  - Verify test isolation (no shared state between tests)
  - Assess maintainability and readability
  - Issue APPROVED / NEEDS_REVISION verdict with specific fix items

Pipeline Position:
  Runs AFTER AutomationAgent (code generation), BEFORE test execution.
  If verdict == NEEDS_REVISION, the AutomationAgent is called again
  with the review feedback injected into the prompt.

Architectural Principle:
  AI DECIDES which code issues exist.
  CODE VALIDATES by checking against framework standards.
  HUMAN APPROVES the final generated code before it enters the test suite.
"""


class AutomationReviewAgent:
    """
    Review AI-generated automation code against framework standards and
    issue a formal APPROVED / NEEDS_REVISION verdict.
    """

    def __init__(self, llm) -> None:
        self.llm = llm

    def review(self, generated_code: str, key_scenarios: str, reuse_report: str) -> str:
        """
        Review the generated automation code.

        Parameters
        ----------
        generated_code : str
            Python code generated by AutomationAgent.
        key_scenarios : str
            KeyScenarioAgent output (what the code should test).
        reuse_report : str
            FrameworkReuseAgent output (what components should be used).

        Returns
        -------
        str
            Structured code review report with scorecard, issues list,
            and formal APPROVED / NEEDS_REVISION verdict.
        """
        prompt = f"""
You are a Senior SDET and Code Reviewer with 15+ years of experience in
Python, Pytest, Playwright, and enterprise automation framework governance.
You are the quality gate for all AI-generated automation code.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
YOUR MISSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Review the AI-generated automation code below against the framework
standards and the reuse report. Issue a formal verdict and provide
specific, actionable fix items for every issue found.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GENERATED CODE TO REVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{generated_code}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KEY SCENARIOS (what the code should test)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{key_scenarios}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FRAMEWORK REUSE REPORT (what components MUST be used)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{reuse_report}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REVIEW CRITERIA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Score each dimension 0–10 (10 = perfect):

  1. FRAMEWORK COMPLIANCE (Weight: 25%)
     - Uses `page` fixture from conftest.py (not sync_playwright)
     - Uses POM classes (LoginPage, DashboardPage, etc.) correctly
     - Uses XLUtils.read_api_data_from_excel() for all test data
     - Uses result() from common_modules for pass/fail logging
     - Uses core.e2e_testData for URL/credentials (no hardcoding)
     - Follows existing naming conventions (TestFeature, test_method)

  2. ASSERTION QUALITY (Weight: 20%)
     - Every test has at least one meaningful assertion
     - Assertions are specific and measurable
     - result() is called with correct status (passed/failed)
     - try/except wraps all UI interactions with result("failed") on catch

  3. ALLURE INTEGRATION (Weight: 15%)
     - @allure.feature on class
     - @allure.story and @allure.title on each test method
     - @allure.severity on each test method
     - with allure.step() wraps each logical step

  4. TEST ISOLATION (Weight: 15%)
     - No shared mutable state between test methods
     - Each test sets up its own preconditions
     - No test depends on another test's side effects
     - No global variables modified by tests

  5. RELIABILITY & FLAKINESS (Weight: 15%)
     - No time.sleep() calls (use Playwright waits)
     - No hardcoded waits or arbitrary timeouts
     - Locators are stable (prefer role/text over fragile CSS)
     - No race conditions in async operations

  6. CODE QUALITY (Weight: 10%)
     - PEP8 compliant (4-space indent, snake_case, max 100 chars/line)
     - Meaningful docstrings on class and methods
     - No dead code or commented-out blocks
     - Arrange/Act/Assert structure with comments

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REQUIRED OUTPUT SECTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

## 1. CODE REVIEW SCORECARD

| Review Dimension      | Score (0-10) | Weight | Weighted Score | Notes |
|-----------------------|--------------|--------|----------------|-------|
| Framework Compliance  | X/10         | 25%    | X.XX           | ...   |
| Assertion Quality     | X/10         | 20%    | X.XX           | ...   |
| Allure Integration    | X/10         | 15%    | X.XX           | ...   |
| Test Isolation        | X/10         | 15%    | X.XX           | ...   |
| Reliability           | X/10         | 15%    | X.XX           | ...   |
| Code Quality          | X/10         | 10%    | X.XX           | ...   |
| **OVERALL**           | **X.XX/10**  | 100%   | **X.XX**       |       |

## 2. CRITICAL ISSUES (must fix before APPROVED)

For each critical issue:
  ISSUE-[NNN] | Severity: CRITICAL | Line: [N] | Description: [What is wrong]
              | Fix: [Exact code change required]

## 3. MAJOR ISSUES (should fix)

  ISSUE-[NNN] | Severity: MAJOR | Line: [N] | Description: [What is wrong]
              | Fix: [Exact code change required]

## 4. MINOR ISSUES (nice to fix)

  ISSUE-[NNN] | Severity: MINOR | Line: [N] | Description: [What is wrong]
              | Fix: [Suggested improvement]

## 5. FRAMEWORK COMPLIANCE CHECK

  ✅/❌ Uses `page` fixture from conftest.py
  ✅/❌ Uses POM classes (not raw Playwright calls)
  ✅/❌ Reads test data from Excel via XLUtils
  ✅/❌ Uses result() for pass/fail logging
  ✅/❌ No hardcoded URLs/credentials
  ✅/❌ @allure.feature on class
  ✅/❌ @allure.story/@allure.title on each method
  ✅/❌ with allure.step() on each logical step
  ✅/❌ try/except with result("failed") on assertions
  ✅/❌ No time.sleep() calls
  ✅/❌ Follows PEP8 naming conventions

## 6. SCENARIO COVERAGE CHECK

For each KS-XXX from the key scenarios:
  KS-[NNN] | [Scenario title] | Covered: [YES | NO | PARTIAL] | Test method: [method_name]

## 7. FORMAL VERDICT

  ┌─────────────────────────────────────────────────────────────────────┐
  │  VERDICT: [APPROVED | NEEDS_REVISION]                               │
  └─────────────────────────────────────────────────────────────────────┘

  Verdict Criteria:
    APPROVED       → Overall score ≥ 8.0, zero CRITICAL issues
    NEEDS_REVISION → Overall score < 8.0, OR any CRITICAL issue exists

  Verdict Justification:
  [2-3 sentences with specific evidence]

  If NEEDS_REVISION — Required fixes before re-review:
  [Numbered list of specific changes required]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ DO:
  - Reference specific line numbers when flagging issues
  - Provide exact code fixes (not just "fix the assertion")
  - Check EVERY test method for framework compliance
  - Verify ALL key scenarios are covered by test methods

❌ DO NOT:
  - Issue APPROVED if any CRITICAL issue exists
  - Use vague feedback like "improve code quality"
  - Skip the scenario coverage check
  - Omit the framework compliance checklist
"""
        return self.llm.generate(prompt)
