"""
RTM Agent (Requirement Traceability Matrix)
===========================================
QA Manager agent that generates a complete 10-column RTM.

RTM Column Structure:
  Requirement ID | User Story | API Name | Test Case ID | Test Scenario |
  Priority | Test Type | Automation | Status | Defect ID
"""


class RTMAgent:
    """Generate a complete RTM using the standard enterprise column format."""

    def __init__(self, llm) -> None:
        self.llm = llm

    def generate_rtm(
        self,
        requirement: str,
        analysis: str,
        test_cases: str,
        key_scenarios: str,
        review: str,
        recommendation: str,
        defects: str,
    ) -> str:
        prompt = f"""
You are a Senior QA Manager and Compliance Lead with 15+ years of experience
in quality assurance governance and requirement traceability.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RTM COLUMN STRUCTURE (MANDATORY — use exactly these 10 columns):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

| Requirement ID | User Story | API Name | Test Case ID | Test Scenario | Priority | Test Type | Automation | Status | Defect ID |

ORIGINAL REQUIREMENT:
{requirement}

REQUIREMENT ANALYSIS (REQ-XXX anchors):
{analysis}

TEST CASES (TC-XXX-NNN with RTM links):
{test_cases}

KEY SCENARIOS (KS-XXX with ROI scores):
{key_scenarios}

REVIEW VERDICT & GAP ANALYSIS:
{review}

AUTOMATION RECOMMENDATIONS:
{recommendation}

DEFECT PREDICTIONS & RISK REGISTER:
{defects}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REQUIRED OUTPUT SECTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

## 1. RTM HEADER (Project, Generated By, Pipeline Verdict, Version, Date, totals)
## 2. REQUIREMENT TRACEABILITY MATRIX (full 10-column table — one row per test case)
## 3. RTM SUMMARY BY REQUIREMENT
## 4. COVERAGE METRICS DASHBOARD
## 5. COVERAGE GAP REPORT
## 6. COMPLIANCE READINESS SCORE (0-100)
## 7. RTM JSON EXPORT
## 8. EXECUTIVE SUMMARY

OUTPUT RULES:
✅ Use EXACTLY the 10 columns in the specified order
✅ Create one RTM row per test case (not one row per requirement)
✅ Use "Not Executed" for Status on all newly generated test cases
✅ Use "NA" for Defect ID when no defect exists
✅ Include EVERY REQ-XXX from the analysis
❌ Do NOT leave any cell empty — use "N/A" or "NA" as appropriate
"""
        return self.llm.generate(prompt)
