# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
"""
Add Employee Feature — Automated Test Suite
============================================
Story ID  : HRM-201
Feature   : PIM → Add Employee (OrangeHRM)
Requirement:
  As an HR Administrator I want to Add a new employee so that Employee
  details are maintained in the system.

Acceptance Criteria:
  AC-1  Navigate to PIM → Employee List is visible
  AC-2  Click Add Employee → Add Employee form is visible
  AC-3  Enter mandatory details (First Name, Last Name) → Click Save
  AC-4  Employee is created successfully → Personal Details page shown
  AC-5  Employee ID is auto-generated and non-empty
  AC-6  Employee appears in Employee List after creation

Framework components reused:
  - PIMPage          (core/ui/pages/pim_page.py)
  - PIMLocator       (core/ui/locators/pim_locator.py)
  - LoginPage        (core/ui/pages/login_page.py)
  - DashboardPage    (core/ui/pages/dashboard_page.py)
  - LeftMenu         (core/ui/components/left_menu.py)
  - conftest.py      `page` fixture (browser, video, tracing, Allure attachments)
  - XLUtils          read_api_data_from_excel(), read_cloud_env()
  - common_modules   result()
  - e2e_testData     url, username, password

Test Cases Covered:
  TC-EMP-001  Add employee with valid mandatory fields only (First Name + Last Name)
  TC-EMP-002  Add employee with all fields including Create Login Details
  TC-EMP-003  Add employee with missing First Name — Required field validation
  TC-EMP-004  Add employee with missing Last Name — Required field validation
  TC-EMP-005  Add employee with both mandatory fields missing — Required field validation
  TC-EMP-006  Add employee with duplicate Employee ID — Already exists error
  TC-EMP-007  Add employee with mismatched passwords — Password mismatch error
  TC-EMP-008  Verify employee appears in Employee List after creation
  TC-EMP-009  Cancel Add Employee form navigates back to Employee List
  TC-EMP-010  Add employee with custom Employee ID — ID saved correctly
  TC-EMP-011  Boundary — First Name at maximum allowed length (30 chars)
  TC-EMP-012  Boundary — First Name at minimum length (1 char)
  TC-EMP-013  Security — SQL injection payload in First Name field
  TC-EMP-014  Security — XSS payload in First Name field
"""

import allure
import pytest

from core.common_modules import result
from core.e2e_testData import url, username, password, storage_state_path
from core.ui.pages.login_page import LoginPage
from core.ui.session_manager import SessionManager
from core.ui.pages.dashboard_page import DashboardPage
from core.ui.pages.pim_page import PIMPage
from core.utils.XLUtils import read_api_data_from_excel, read_cloud_env





# ─────────────────────────────────────────────────────────────────────────────
# Test Class
# ─────────────────────────────────────────────────────────────────────────────

@allure.feature("Add Employee")
class TestAddEmployee:
    """
    End-to-end test suite for the PIM → Add Employee feature (HRM-201).

    Pre-conditions for all tests:
      - Application is accessible at the configured URL
      - A valid HR Administrator account exists (credentials from Excel / e2e_testData)
      - The `page` fixture from conftest.py provides a pre-configured Playwright browser
      - testData/API_testData.xlsx contains the Web_UI sheet with test data rows
    """

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-001: Add employee with valid mandatory fields only
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Valid Employee Creation")
    @allure.title("TC-EMP-001: Add employee with valid mandatory fields (First Name + Last Name)")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_add_employee_valid_mandatory_fields(self, page):
        """
        Verify that an HR Administrator can add a new employee by providing
        only the mandatory fields (First Name and Last Name).

        RTM Link : REQ-001 (Employee must be created with mandatory fields)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter First Name and Last Name from Excel test data
          4. Click Save
          5. Verify Personal Details page is displayed (employee created)
          6. Verify Employee ID is auto-generated (non-empty)

        Expected Result:
          - Personal Details page loads after Save
          - A non-empty Employee ID is displayed
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Valid")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name  = data.get("FirstName",  "Alice")
        last_name   = data.get("LastName",   "Johnson")
        employee_id = data.get("EmployeeID", "")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Verify Add Employee form is displayed"):
            try:
                pim_page.verify_add_employee_form()
                result("passed", "Add Employee form should be visible",
                       "Add Employee form is visible")
            except Exception as exc:
                result("failed", "Add Employee form should be visible",
                       f"Form NOT visible: {exc}")
                raise

        with allure.step(f"Fill mandatory fields: FirstName='{first_name}', LastName='{last_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
                employee_id=employee_id,
            )

        with allure.step("Click Save button"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify Personal Details page is displayed (employee created)"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Personal Details page should be visible after Save",
                       "Personal Details page is visible — employee created successfully")
            except Exception as exc:
                result("failed",
                       "Personal Details page should be visible after Save",
                       f"Personal Details page NOT visible: {exc}")
                raise

        with allure.step("Verify Employee ID is auto-generated (non-empty)"):
            try:
                generated_id = pim_page.get_employee_id()
                assert generated_id and generated_id.strip(), \
                    "Employee ID should not be empty after creation"
                result("passed",
                       "Employee ID should be auto-generated and non-empty",
                       f"Employee ID generated: '{generated_id}'")
            except AssertionError as exc:
                result("failed",
                       "Employee ID should be auto-generated and non-empty",
                       f"Employee ID is empty: {exc}")
                raise
            except Exception as exc:
                result("failed",
                       "Employee ID should be auto-generated and non-empty",
                       f"Could not read Employee ID: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-002: Add employee with all fields including Create Login Details
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Valid Employee Creation")
    @allure.title("TC-EMP-002: Add employee with all fields including Create Login Details")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_add_employee_with_login_details(self, page):
        """
        Verify that an HR Administrator can add a new employee with all fields
        filled in, including enabling 'Create Login Details' with a username
        and matching password.

        RTM Link : REQ-001, REQ-002 (Employee created; login credentials set)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter First Name, Middle Name, Last Name, Employee ID
          4. Enable 'Create Login Details' toggle
          5. Enter Username, Password, Confirm Password (matching)
          6. Click Save
          7. Verify Personal Details page is displayed

        Expected Result:
          - Personal Details page loads after Save
          - Employee with login credentials is created successfully
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        # Use a timestamp-based unique username to avoid "Already exists" errors
        import time as _time
        _ts = str(int(_time.time()))[-6:]
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_WithLogin")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name       = data.get("FirstName",       "Robert")
        middle_name      = data.get("MiddleName",      "James")
        last_name        = data.get("LastName",        "Williams")
        # Always generate a unique username — never reuse a static one
        login_username   = f"rw{_ts}"
        login_password   = data.get("LoginPassword",   "SecurePass1!")
        confirm_password = data.get("ConfirmPassword", "SecurePass1!")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Fill all employee name fields"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
                middle_name=middle_name,
            )

        with allure.step("Enable 'Create Login Details' toggle and fill credentials"):
            try:
                pim_page.enable_create_login()
                pim_page.enter_login_username(login_username)
                pim_page.enter_login_password(login_password)
                pim_page.enter_confirm_password(confirm_password)
                result("passed",
                       "Login details fields should be fillable after enabling toggle",
                       f"Login details filled — username='{login_username}'")
            except Exception as exc:
                result("failed",
                       "Login details fields should be fillable after enabling toggle",
                       f"Could not fill login details: {exc}")
                raise

        with allure.step("Click Save button"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify Personal Details page is displayed"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Personal Details page should be visible after Save",
                       "Personal Details page is visible — employee with login created")
            except Exception as exc:
                result("failed",
                       "Personal Details page should be visible after Save",
                       f"Personal Details page NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-003: Add employee with missing First Name (required field)
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Required Field Validation")
    @allure.title("TC-EMP-003: Add employee with missing First Name — Required field error")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_missing_first_name(self, page):
        """
        Verify that submitting the Add Employee form without a First Name
        displays a 'Required' validation error and does NOT create the employee.

        RTM Link : REQ-003 (Mandatory fields must be validated)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Leave First Name empty, enter Last Name only
          4. Click Save
          5. Verify 'Required' error is displayed

        Expected Result:
          - Form stays on Add Employee page
          - 'Required' validation error is visible
          - Employee is NOT created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_MissingFirstName")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        last_name = data.get("LastName", "Thompson")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Enter Last Name only (leave First Name empty)"):
            pim_page.enter_last_name(last_name)

        with allure.step("Click Save without entering First Name"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify 'Required' validation error is displayed for First Name"):
            try:
                pim_page.verify_required_field_error()
                result("passed",
                       "'Required' error should appear when First Name is missing",
                       "'Required' validation error is visible")
            except Exception as exc:
                result("failed",
                       "'Required' error should appear when First Name is missing",
                       f"'Required' error NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-004: Add employee with missing Last Name (required field)
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Required Field Validation")
    @allure.title("TC-EMP-004: Add employee with missing Last Name — Required field error")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_missing_last_name(self, page):
        """
        Verify that submitting the Add Employee form without a Last Name
        displays a 'Required' validation error and does NOT create the employee.

        RTM Link : REQ-003 (Mandatory fields must be validated)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter First Name only, leave Last Name empty
          4. Click Save
          5. Verify 'Required' error is displayed

        Expected Result:
          - Form stays on Add Employee page
          - 'Required' validation error is visible
          - Employee is NOT created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_MissingLastName")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "Michael")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Enter First Name only (leave Last Name empty)"):
            pim_page.enter_first_name(first_name)

        with allure.step("Click Save without entering Last Name"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify 'Required' validation error is displayed for Last Name"):
            try:
                pim_page.verify_required_field_error()
                result("passed",
                       "'Required' error should appear when Last Name is missing",
                       "'Required' validation error is visible")
            except Exception as exc:
                result("failed",
                       "'Required' error should appear when Last Name is missing",
                       f"'Required' error NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-005: Add employee with both mandatory fields missing
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Required Field Validation")
    @allure.title("TC-EMP-005: Add employee with both First Name and Last Name missing — Required errors")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_missing_both_mandatory_fields(self, page):
        """
        Verify that submitting the Add Employee form with both First Name and
        Last Name empty displays 'Required' validation errors for both fields.

        RTM Link : REQ-003 (Mandatory fields must be validated)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Leave both First Name and Last Name empty
          4. Click Save
          5. Verify 'Required' errors are displayed

        Expected Result:
          - 'Required' validation errors are visible for both fields
          - Employee is NOT created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Click Save without entering any name fields"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify 'Required' validation errors are displayed"):
            try:
                pim_page.verify_required_field_error()
                result("passed",
                       "'Required' errors should appear when both name fields are missing",
                       "'Required' validation error(s) are visible")
            except Exception as exc:
                result("failed",
                       "'Required' errors should appear when both name fields are missing",
                       f"'Required' error(s) NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-006: Add employee with duplicate Employee ID
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Duplicate Employee ID Validation")
    @allure.title("TC-EMP-006: Add employee with duplicate Employee ID — Already exists error")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_duplicate_employee_id(self, page):
        """
        Verify that entering an Employee ID that already exists in the system
        displays an 'Already exists' error and prevents employee creation.

        RTM Link : REQ-004 (Employee ID must be unique)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter valid First Name and Last Name
          4. Enter an Employee ID that already exists (e.g., "0001")
          5. Click Save
          6. Verify 'Already exists' error is displayed

        Expected Result:
          - 'Already exists' validation error is visible
          - Employee is NOT created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_DuplicateID")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name  = data.get("FirstName",  "Duplicate")
        last_name   = data.get("LastName",   "TestUser")
        employee_id = data.get("EmployeeID", "0001")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Fill form with duplicate Employee ID: '{employee_id}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
                employee_id=employee_id,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify 'Already exists' error is displayed"):
            try:
                pim_page.verify_already_exists_error()
                result("passed",
                       "'Already exists' error should appear for duplicate Employee ID",
                       f"'Already exists' error is visible for Employee ID '{employee_id}'")
            except Exception as exc:
                result("failed",
                       "'Already exists' error should appear for duplicate Employee ID",
                       f"'Already exists' error NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-007: Add employee with mismatched passwords
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Password Validation")
    @allure.title("TC-EMP-007: Add employee with mismatched passwords — Password mismatch error")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_password_mismatch(self, page):
        """
        Verify that entering mismatched Password and Confirm Password values
        in the Create Login Details section displays a 'Passwords do not match'
        error and prevents employee creation.

        RTM Link : REQ-005 (Password and Confirm Password must match)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter valid First Name and Last Name
          4. Enable 'Create Login Details' toggle
          5. Enter Password and a different Confirm Password
          6. Click Save
          7. Verify 'Passwords do not match' error is displayed

        Expected Result:
          - 'Passwords do not match' validation error is visible
          - Employee is NOT created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_PasswordMismatch")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name       = data.get("FirstName",       "Sarah")
        last_name        = data.get("LastName",        "Connor")
        login_username   = data.get("LoginUsername",   "sconnor_test")
        login_password   = data.get("LoginPassword",   "Password123!")
        confirm_password = data.get("ConfirmPassword", "DifferentPass456!")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Fill employee name fields"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Enable Create Login Details and enter mismatched passwords"):
            pim_page.enable_create_login()
            pim_page.enter_login_username(login_username)
            pim_page.enter_login_password(login_password)
            pim_page.enter_confirm_password(confirm_password)

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify 'Passwords do not match' error is displayed"):
            try:
                pim_page.verify_password_mismatch_error()
                result("passed",
                       "'Passwords do not match' error should appear for mismatched passwords",
                       "'Passwords do not match' error is visible")
            except Exception as exc:
                result("failed",
                       "'Passwords do not match' error should appear for mismatched passwords",
                       f"Password mismatch error NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-008: Verify employee appears in Employee List after creation
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Employee List Verification")
    @allure.title("TC-EMP-008: Verify newly added employee appears in Employee List")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_employee_appears_in_list_after_creation(self, page):
        """
        Verify that after successfully adding an employee, the employee can be
        found in the Employee List by searching with their name.

        RTM Link : REQ-006 (Employee must appear in Employee List after creation)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter First Name and Last Name
          4. Click Save and verify Personal Details page
          5. Navigate back to Employee List (PIM)
          6. Search for the employee by name
          7. Verify at least one result row is visible

        Expected Result:
          - Employee List shows at least one result for the searched name
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_VerifyInList")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "Emma")
        last_name  = data.get("LastName",  "Davis")
        full_name  = f"{first_name} {last_name}"

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Fill Add Employee form: '{first_name} {last_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        with allure.step("Verify Personal Details page is displayed (employee saved)"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Personal Details page should be visible after Save",
                       "Employee saved — Personal Details page visible")
            except Exception as exc:
                result("failed",
                       "Personal Details page should be visible after Save",
                       f"Personal Details page NOT visible: {exc}")
                raise

        with allure.step("Navigate back to Employee List via PIM menu"):
            pim_page.navigate_to_pim()

        with allure.step(f"Search for employee by name: '{full_name}'"):
            pim_page.search_employee_by_name(full_name)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify employee appears in search results"):
            try:
                pim_page.verify_employee_in_list()
                row_count = pim_page.get_employee_row_count()
                result("passed",
                       f"Employee '{full_name}' should appear in Employee List",
                       f"Employee found in list — {row_count} row(s) returned")
            except Exception as exc:
                result("failed",
                       f"Employee '{full_name}' should appear in Employee List",
                       f"Employee NOT found in list: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-009: Cancel Add Employee form navigates back to Employee List
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Cancel Navigation")
    @allure.title("TC-EMP-009: Cancel Add Employee form returns to Employee List")
    @allure.severity(allure.severity_level.NORMAL)
    def test_cancel_add_employee_returns_to_list(self, page):
        """
        Verify that clicking the Cancel button on the Add Employee form
        navigates back to the Employee List page without creating an employee.

        RTM Link : REQ-007 (Cancel must discard changes and return to list)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter some data in the form
          4. Click Cancel
          5. Verify Employee List page is displayed

        Expected Result:
          - Employee List page is displayed after Cancel
          - No employee is created
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Cancel")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "CancelTest")
        last_name  = data.get("LastName",  "User")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step("Enter partial data in the form"):
            pim_page.enter_first_name(first_name)
            pim_page.enter_last_name(last_name)

        with allure.step("Click Cancel button"):
            pim_page.click_cancel()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify Employee List page is displayed after Cancel"):
            try:
                pim_page.verify_employee_list_page()
                result("passed",
                       "Employee List page should be displayed after Cancel",
                       "Employee List page is visible — Cancel navigated back correctly")
            except Exception as exc:
                result("failed",
                       "Employee List page should be displayed after Cancel",
                       f"Employee List page NOT visible after Cancel: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-010: Add employee with custom Employee ID
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Custom Employee ID")
    @allure.title("TC-EMP-010: Add employee with custom Employee ID — ID saved correctly")
    @allure.severity(allure.severity_level.NORMAL)
    def test_add_employee_custom_employee_id(self, page):
        """
        Verify that a custom Employee ID entered by the user is saved and
        displayed correctly on the Personal Details page.

        RTM Link : REQ-008 (Custom Employee ID must be persisted)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter valid First Name and Last Name
          4. Clear the auto-generated Employee ID and enter a custom one
          5. Click Save
          6. Verify Personal Details page is displayed
          7. Verify the Employee ID matches the custom value entered

        Expected Result:
          - Personal Details page shows the custom Employee ID that was entered
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        import time as _time2
        _unique_id = str(int(_time2.time()))[-4:]   # 4-digit numeric unique ID
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_CustomID")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name  = data.get("FirstName",  "Custom")
        last_name   = data.get("LastName",   "IDTest")
        employee_id = data.get("EmployeeID", _unique_id)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Fill form with custom Employee ID: '{employee_id}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
                employee_id=employee_id,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        with allure.step("Verify Personal Details page is displayed"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Personal Details page should be visible after Save",
                       "Personal Details page is visible")
            except Exception as exc:
                result("failed",
                       "Personal Details page should be visible after Save",
                       f"Personal Details page NOT visible: {exc}")
                raise

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step(f"Verify Employee ID matches custom value: '{employee_id}'"):
            try:
                saved_id = pim_page.get_employee_id()
                assert saved_id.strip() == employee_id.strip(), \
                    f"Expected Employee ID '{employee_id}' but got '{saved_id}'"
                result("passed",
                       f"Employee ID should be '{employee_id}'",
                       f"Employee ID is '{saved_id}' — matches custom value")
            except AssertionError as exc:
                result("failed",
                       f"Employee ID should be '{employee_id}'",
                       f"Employee ID mismatch: {exc}")
                raise
            except Exception as exc:
                result("failed",
                       f"Employee ID should be '{employee_id}'",
                       f"Could not read Employee ID: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-011: Boundary — First Name at maximum allowed length (30 chars)
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Boundary Value Testing")
    @allure.title("TC-EMP-011: Add employee with First Name at maximum boundary length (30 chars)")
    @allure.severity(allure.severity_level.MINOR)
    def test_add_employee_first_name_max_boundary(self, page):
        """
        Verify that an employee can be added with a First Name at the maximum
        allowed boundary length (30 characters).

        RTM Link : REQ-009 (First Name boundary: max 30 chars)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter a First Name of exactly 30 characters
          4. Enter a valid Last Name
          5. Click Save
          6. Verify Personal Details page is displayed (boundary value accepted)

        Expected Result:
          - Employee is created successfully with a 30-character First Name
          - Personal Details page is displayed
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        _max_first_name = "A" * 30   # 30 chars — boundary value
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Boundary_MaxFirstName")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", _max_first_name)[:30]   # enforce max
        last_name  = data.get("LastName",  "BoundaryTest")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Enter First Name at max boundary (30 chars): '{first_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify Personal Details page is displayed (30-char First Name accepted)"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Employee should be created with First Name at max boundary (30 chars)",
                       "Personal Details page visible — 30-char First Name accepted")
            except Exception as exc:
                result("failed",
                       "Employee should be created with First Name at max boundary (30 chars)",
                       f"Personal Details page NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-012: Boundary — First Name at minimum length (1 char)
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Boundary Value Testing")
    @allure.title("TC-EMP-012: Add employee with First Name at minimum boundary length (1 char)")
    @allure.severity(allure.severity_level.MINOR)
    def test_add_employee_first_name_min_boundary(self, page):
        """
        Verify that an employee can be added with a First Name of exactly
        1 character (minimum boundary value).

        RTM Link : REQ-009 (First Name boundary: min 1 char)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter a First Name of exactly 1 character
          4. Enter a valid Last Name
          5. Click Save
          6. Verify Personal Details page is displayed (boundary value accepted)

        Expected Result:
          - Employee is created successfully with a 1-character First Name
          - Personal Details page is displayed
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Boundary_MinFirstName")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "A")[:1]   # enforce min = 1 char
        last_name  = data.get("LastName",  "MinBoundary")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Enter First Name at min boundary (1 char): '{first_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify Personal Details page is displayed (1-char First Name accepted)"):
            try:
                pim_page.verify_personal_details_page()
                result("passed",
                       "Employee should be created with First Name at min boundary (1 char)",
                       "Personal Details page visible — 1-char First Name accepted")
            except Exception as exc:
                result("failed",
                       "Employee should be created with First Name at min boundary (1 char)",
                       f"Personal Details page NOT visible: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-013: Security — SQL injection payload in First Name field
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Security Testing")
    @allure.title("TC-EMP-013: SQL injection payload in First Name field — Rejected or sanitized")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_add_employee_sql_injection_first_name(self, page):
        """
        Verify that entering a SQL injection payload in the First Name field
        does NOT cause a database error, does NOT expose SQL error messages,
        and is either rejected with a validation error or safely sanitized.

        RTM Link : REQ-010 (OWASP A03:2021 — Injection prevention)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter SQL injection payload in First Name: ' OR '1'='1
          4. Enter a valid Last Name
          5. Click Save
          6. Verify no SQL error is exposed in the page content

        Expected Result:
          - Application does NOT display a raw SQL error message
          - Input is either rejected with a validation error OR sanitized
          - No database exception is thrown to the UI
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Security_SQLInject")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "' OR '1'='1")
        last_name  = data.get("LastName",  "SecurityTest")

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Enter SQL injection payload in First Name: '{first_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify no SQL error is exposed — application handles input safely"):
            try:
                page_content = page.content()
                sql_error_keywords = [
                    "sql", "syntax error", "mysql", "postgresql",
                    "ora-", "sqlite", "unclosed quotation", "unterminated string",
                    "database error", "db error",
                ]
                exposed = any(kw in page_content.lower() for kw in sql_error_keywords)
                assert not exposed, (
                    "SQL error keywords found in page content — "
                    "application may be vulnerable to SQL injection!"
                )
                result("passed",
                       "No SQL error should be exposed in the UI for SQL injection input",
                       "No SQL error keywords found — input handled safely")
            except AssertionError as exc:
                result("failed",
                       "No SQL error should be exposed in the UI for SQL injection input",
                       f"SECURITY RISK — SQL error exposed: {exc}")
                raise
            except Exception as exc:
                result("failed",
                       "No SQL error should be exposed in the UI for SQL injection input",
                       f"Unexpected error during security check: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-EMP-014: Security — XSS payload in First Name field
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Security Testing")
    @allure.title("TC-EMP-014: XSS payload in First Name field — No script execution")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_add_employee_xss_first_name(self, page):
        """
        Verify that entering an XSS payload in the First Name field does not
        result in script execution. The input should be sanitized or rejected.

        RTM Link : REQ-010 (OWASP A03:2021 — XSS prevention)
        Steps:
          1. Login as HR Administrator
          2. Navigate to PIM → Add Employee
          3. Enter XSS payload in First Name: <script>alert('xss')</script>
          4. Enter a valid Last Name
          5. Click Save
          6. Verify no JavaScript alert is triggered

        Expected Result:
          - No JavaScript alert is triggered
          - XSS payload is sanitized or rejected
          - Application remains stable
        """
        # ── Arrange ──────────────────────────────────────────────────────────
        cloud_env = read_cloud_env()
        try:
            data = read_api_data_from_excel("Web_UI", "TC_AddEmployee_Security_XSS")
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            data = {}
        first_name = data.get("FirstName", "<script>alert('xss')</script>")
        last_name  = data.get("LastName",  "XSSTest")

        # Track if a dialog (alert) is triggered by the XSS payload
        alert_triggered = {"value": False, "message": ""}

        def _handle_dialog(dialog):
            alert_triggered["value"] = True
            alert_triggered["message"] = dialog.message
            dialog.dismiss()

        page.on("dialog", _handle_dialog)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
            login_page = LoginPage(page)
            try:
                login_page.verify_dashboard()
            except Exception as exc:
                result("failed", "Dashboard should be visible after login",
                       f"Dashboard NOT visible: {exc}")
                raise
            pim_page = PIMPage(page)
            pim_page.navigate_to_pim()
            pim_page.click_add_employee()

        with allure.step(f"Enter XSS payload in First Name: '{first_name}'"):
            pim_page.fill_add_employee_form(
                first_name=first_name,
                last_name=last_name,
            )

        with allure.step("Click Save"):
            pim_page.click_save()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify no JavaScript alert was triggered (XSS sanitized)"):
            try:
                assert not alert_triggered["value"], (
                    f"XSS alert was triggered with message: "
                    f"'{alert_triggered['message']}' — input was NOT sanitized!"
                )
                result("passed",
                       "No JavaScript alert should be triggered when XSS payload is entered",
                       "No alert triggered — XSS payload was sanitized or rejected")
            except AssertionError as exc:
                result("failed",
                       "No JavaScript alert should be triggered when XSS payload is entered",
                       f"SECURITY RISK — XSS alert was triggered: {exc}")
                raise
            except Exception as exc:
                result("failed",
                       "No JavaScript alert should be triggered when XSS payload is entered",
                       f"Unexpected error during XSS check: {exc}")
                raise
