# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
import allure
import pytest

from core.common_modules import result
from core.e2e_testData import storage_state_path, url, username, password
from core.ui.pages.dashboard_page import DashboardPage
from core.ui.pages.leave_page import LeaveApplyPage
from core.ui.pages.login_page import LoginPage
from core.ui.pages.leave_page import MyLeavePage
from core.ui.session_manager import SessionManager
from core.utils.XLUtils import read_api_data_from_excel

SHEET_NAME = "LeaveApply"


@allure.feature("Apply for Leave")
class TestLeaveApply:
    """
    Test suite covering the Apply for Leave feature in OrangeHRM.
    Scenarios: KS-001 through KS-006
    Priority: P1-CRITICAL (KS-001, KS-002, KS-003, KS-005) |
              P2-HIGH     (KS-004, KS-006)
    """

    # ─────────────────────────────────────────────────────────────────────────
    # KS-001 | P1-CRITICAL | ROI 4.75
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Happy Path — Full Leave Application Submission (E2E)")
    @allure.title("KS-001: Happy Path — Full Leave Application Submission (E2E)")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.parametrize("testcase", ["KS-001"])
    @pytest.mark.ui
    def test_ks001_happy_path_full_leave_submission(self, page, testcase):
        """
        RTM: REQ-001, REQ-002, REQ-003, REQ-004, REQ-005, REQ-006, REQ-007, REQ-012
        Validates the complete end-to-end leave application workflow.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type       = str(data.get("leave_type",       "Annual Leave"))
            from_date        = str(data.get("from_date",        "2025-09-01"))
            to_date          = str(data.get("to_date",          "2025-09-02"))
            comment          = str(data.get("comment",          "Automated test leave"))
            expected_duration = str(data.get("expected_duration", "2.0 Day(s)"))
            expected_status  = str(data.get("expected_status",  "Pending Approval"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)
            my_leave_page    = MyLeavePage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Select leave type"):
            leave_apply_page.select_leave_type(leave_type)

        with allure.step("Act: Enter From Date and To Date"):
            leave_apply_page.enter_from_date(from_date)
            leave_apply_page.enter_to_date(to_date)

        with allure.step("Act: Enter optional comment"):
            leave_apply_page.enter_comments(comment)

        with allure.step("Act: Submit the leave application"):
            leave_apply_page.click_apply()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Assert: Verify submission success confirmation"):
            try:
                assert leave_apply_page.is_success_shown(), \
                    "Leave submission success indicator not found after Apply"
                result("passed",
                       "Leave application submitted successfully",
                       "Submission success confirmation displayed")
            except AssertionError as exc:
                result("failed",
                       "Leave application submitted successfully",
                       str(exc))
                raise

        with allure.step("Assert: Verify leave record appears in My Leave"):
            dashboard_page.navigate_to_leave()
            my_leave_page.navigate_to_my_leave()
            try:
                assert my_leave_page.find_leave_request(leave_type, from_date, to_date), \
                    f"Leave record for '{leave_type}' ({from_date}–{to_date}) not found"
                result("passed",
                       "Leave record visible in My Leave list",
                       "Leave record found in My Leave list")
            except AssertionError as exc:
                result("failed",
                       "Leave record visible in My Leave list",
                       str(exc))
                raise

        with allure.step("Assert: Verify leave status is Pending Approval"):
            actual_status = my_leave_page.get_leave_status(leave_type, from_date)
            try:
                assert actual_status == expected_status, \
                    f"Status mismatch — expected '{expected_status}', got '{actual_status}'"
                result("passed",
                       f"Leave status is '{expected_status}'",
                       f"Leave status is '{actual_status}'")
            except AssertionError as exc:
                result("failed",
                       f"Leave status is '{expected_status}'",
                       str(exc))
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # KS-002 | P1-CRITICAL | ROI 4.75
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Invalid Date Range Rejection — From Date After To Date")
    @allure.title("KS-002: Invalid Date Range Rejection — From Date After To Date")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.parametrize("testcase", [
        "KS-002-TC01", "KS-002-TC02", "KS-002-TC03", "KS-002-TC04", "KS-002-TC05",
    ])
    @pytest.mark.ui
    def test_ks002_invalid_date_range_rejection(self, page, testcase):
        """
        RTM: REQ-003, REQ-008, REQ-010
        Verifies the system prevents submission when From Date is after To Date.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type                = str(data.get("leave_type",                "Annual Leave"))
            from_date                 = str(data.get("from_date",                 "2025-09-02"))
            to_date                   = str(data.get("to_date",                   "2025-09-01"))
            expected_validation_message = str(data.get("expected_validation_message", "To date should be after from date"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Select leave type"):
            leave_apply_page.select_leave_type(leave_type)

        with allure.step("Act: Enter invalid date range (From Date after To Date)"):
            leave_apply_page.enter_from_date(from_date)
            leave_apply_page.enter_to_date(to_date)

        with allure.step("Act: Attempt to submit"):
            leave_apply_page.click_apply()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Assert: Verify validation error is displayed"):
            actual_error = leave_apply_page.get_error_text()
            try:
                assert expected_validation_message in actual_error, \
                    f"Expected '{expected_validation_message}' in '{actual_error}'"
                result("passed",
                       f"Validation message '{expected_validation_message}' displayed",
                       f"Error message: '{actual_error}'")
            except AssertionError as exc:
                result("failed",
                       f"Validation message '{expected_validation_message}' displayed",
                       str(exc))
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # KS-003 | P1-CRITICAL | ROI 4.15
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Insufficient Leave Balance — Submission Blocked")
    @allure.title("KS-003: Insufficient Leave Balance — Submission Blocked")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.parametrize("testcase", ["KS-003"])
    @pytest.mark.ui
    def test_ks003_insufficient_leave_balance_blocked(self, page, testcase):
        """
        RTM: REQ-002, REQ-009, REQ-010
        Validates that submission is blocked when leave balance is insufficient.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type            = str(data.get("leave_type",            "Annual Leave"))
            from_date             = str(data.get("from_date",             "2025-09-01"))
            to_date               = str(data.get("to_date",               "2025-09-30"))
            expected_balance_error = str(data.get("expected_balance_error", "Failed to Submit"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Select leave type with insufficient balance"):
            leave_apply_page.select_leave_type(leave_type)

        with allure.step("Act: Enter date range exceeding available balance"):
            leave_apply_page.enter_from_date(from_date)
            leave_apply_page.enter_to_date(to_date)

        with allure.step("Act: Attempt to submit"):
            leave_apply_page.click_apply()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Assert: Verify balance error is displayed"):
            actual_error = leave_apply_page.get_error_text()
            try:
                assert expected_balance_error in actual_error, \
                    f"Expected '{expected_balance_error}' in '{actual_error}'"
                result("passed",
                       f"Balance error '{expected_balance_error}' displayed",
                       f"Error: '{actual_error}'")
            except AssertionError as exc:
                result("failed",
                       f"Balance error '{expected_balance_error}' displayed",
                       str(exc))
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # KS-004 | P2-HIGH | ROI 4.35
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Mandatory Field Validation — Submit Without Required Fields")
    @allure.title("KS-004: Mandatory Field Validation — Submit Without Required Fields")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.parametrize("testcase", [
        "KS-004-TC01", "KS-004-TC02", "KS-004-TC03", "KS-004-TC04",
    ])
    @pytest.mark.ui
    def test_ks004_mandatory_field_validation(self, page, testcase):
        """
        RTM: REQ-002, REQ-003, REQ-006, REQ-010
        Verifies that missing mandatory fields trigger validation errors.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type           = str(data.get("leave_type",           ""))
            from_date            = str(data.get("from_date",            ""))
            to_date              = str(data.get("to_date",              ""))
            expected_field_error = str(data.get("expected_field_error", "Required"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Fill only non-omitted fields"):
            if leave_type:
                leave_apply_page.select_leave_type(leave_type)
            if from_date:
                leave_apply_page.enter_from_date(from_date)
            if to_date:
                leave_apply_page.enter_to_date(to_date)

        with allure.step("Act: Attempt to submit incomplete form"):
            leave_apply_page.click_apply()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Assert: Verify validation error is displayed"):
            actual_error = leave_apply_page.get_validation_error_text()
            try:
                assert expected_field_error in actual_error, \
                    f"Expected '{expected_field_error}' in '{actual_error}'"
                result("passed",
                       f"Validation error '{expected_field_error}' displayed",
                       f"Error: '{actual_error}'")
            except AssertionError as exc:
                result("failed",
                       f"Validation error '{expected_field_error}' displayed",
                       str(exc))
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # KS-005 | P1-CRITICAL | ROI 4.15
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Duplicate / Overlapping Leave Request Rejection")
    @allure.title("KS-005: Duplicate / Overlapping Leave Request Rejection")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.parametrize("testcase", ["KS-005"])
    @pytest.mark.ui
    def test_ks005_duplicate_overlapping_leave_rejection(self, page, testcase):
        """
        RTM: REQ-003, REQ-006, REQ-008, REQ-011
        Validates that overlapping leave requests are rejected.
        Pre-condition: Seed leave request pre-created via API.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type             = str(data.get("leave_type",             "Annual Leave"))
            overlap_from_date      = str(data.get("overlap_from_date",      "2025-09-01"))
            overlap_to_date        = str(data.get("overlap_to_date",        "2025-09-02"))
            expected_overlap_error = str(data.get("expected_overlap_error", "There is already a leave request"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Select leave type matching the seed request"):
            leave_apply_page.select_leave_type(leave_type)

        with allure.step("Act: Enter overlapping date range"):
            leave_apply_page.enter_from_date(overlap_from_date)
            leave_apply_page.enter_to_date(overlap_to_date)

        with allure.step("Act: Attempt to submit overlapping request"):
            leave_apply_page.click_apply()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Assert: Verify overlap error is displayed"):
            actual_error = leave_apply_page.get_error_text()
            try:
                assert expected_overlap_error in actual_error, \
                    f"Expected '{expected_overlap_error}' in '{actual_error}'"
                result("passed",
                       f"Overlap error '{expected_overlap_error}' displayed",
                       f"Error: '{actual_error}'")
            except AssertionError as exc:
                result("failed",
                       f"Overlap error '{expected_overlap_error}' displayed",
                       str(exc))
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # KS-006 | P2-HIGH | ROI 3.75
    # ─────────────────────────────────────────────────────────────────────────
    @allure.story("Leave Duration Auto-Calculation Accuracy")
    @allure.title("KS-006: Leave Duration Auto-Calculation Accuracy")
    @allure.severity(allure.severity_level.NORMAL)
    @pytest.mark.parametrize("testcase", [
        "KS-006-TC01", "KS-006-TC02", "KS-006-TC03",
        "KS-006-TC04", "KS-006-TC05", "KS-006-TC06",
    ])
    @pytest.mark.ui
    def test_ks006_leave_duration_auto_calculation(self, page, testcase):
        """
        RTM: REQ-003, REQ-004
        Verifies that the system correctly calculates and displays leave duration.
        """
        # ── Arrange: Load test data ───────────────────────────────────────────
        with allure.step("Arrange: Load test data from Excel"):
            try:
                data = read_api_data_from_excel(SHEET_NAME, testcase)
            except Exception as exc:
                print(f"  [TestData] Excel row '{testcase}' not found — using defaults. ({exc})")
                data = {}
            leave_type        = str(data.get("leave_type",        "Annual Leave"))
            from_date         = str(data.get("from_date",         "2025-09-01"))
            to_date           = str(data.get("to_date",           "2025-09-05"))
            expected_duration = str(data.get("expected_duration", "5.0 Day(s)"))

        with allure.step("Arrange: Initialise page objects"):
            login_page       = LoginPage(page)
            dashboard_page   = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)

        with allure.step("Arrange: Establish authenticated session"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Act: Navigate to Leave → Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Select leave type"):
            leave_apply_page.select_leave_type(leave_type)

        with allure.step(f"Act: Enter date range From '{from_date}' To '{to_date}'"):
            leave_apply_page.enter_from_date(from_date)
            leave_apply_page.enter_to_date(to_date)

        with allure.step("Act: Read the auto-calculated leave balance"):
            actual_duration = leave_apply_page.get_balance_text()

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step(f"Assert: Verify duration equals '{expected_duration}'"):
            try:
                assert expected_duration in actual_duration, \
                    f"Expected '{expected_duration}' in balance text '{actual_duration}'"
                result("passed",
                       f"Duration '{expected_duration}' displayed for {from_date}–{to_date}",
                       f"Balance text: '{actual_duration}'")
            except AssertionError as exc:
                result("failed",
                       f"Duration '{expected_duration}' displayed for {from_date}–{to_date}",
                       str(exc))
                raise
