# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
"""
Leave Management Tests — Apply for Leave
=========================================
Story: OHRM-LEAVE-001

Framework components used:
  - LeaveApplyPage    (core/ui/pages/leave_page.py)
  - MyLeavePage       (core/ui/pages/leave_page.py)
  - LeaveApplyLocator (core/ui/locators/leave_locator.py)
  - LoginPage         (core/ui/pages/login_page.py)
  - page fixture      (conftest.py)
  - read_api_data_from_excel (core/utils/XLUtils.py)
  - result()          (core/common_modules.py)

Test Data:
  testData/API_testData.xlsx → sheet: Web_UI
  Row identifiers:
    TC_Leave_HappyPath_Annual  — valid leave application
    TC_Leave_InvalidDate       — invalid date range (From > To)
    TC_Leave_MissingFields     — all mandatory fields empty
"""

import allure
import pytest

from core.common_modules import result
from core.e2e_testData import url, username, password, storage_state_path
from core.ui.pages.login_page import LoginPage
from core.ui.session_manager import SessionManager
from core.ui.pages.leave_page import LeaveApplyPage, MyLeavePage
from core.ui.locators.leave_locator import LeaveApplyLocator
from core.utils.XLUtils import read_api_data_from_excel


@allure.feature("Leave Management")
@pytest.mark.ui
@pytest.mark.regression
class TestLeaveManagement:
    """Test suite for the Leave > Apply for Leave feature (OHRM-LEAVE-001)."""

    # ─────────────────────────────────────────────────────────────────────────
    # TC-LEAVE-001: Happy path — valid leave application
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Apply for Leave — Happy Path")
    @allure.title("TC-LEAVE-001: Employee can apply for leave with valid data")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.smoke
    def test_apply_leave_valid(self, page):
        """
        Verifies that an employee can successfully apply for leave
        with a valid leave type, date range, and optional comment.

        Test Data: testData/API_testData.xlsx → Web_UI → TC_Leave_HappyPath_Annual
        Expected:  Leave request submitted, status = Pending Approval
        """

        # ── Arrange: read test data from Excel, fall back to defaults ─────────
        try:
            data       = read_api_data_from_excel("Web_UI", "TC_Leave_HappyPath_Annual")
            leave_type = str(data.get("LeaveType", "Annual Leave"))
            from_date  = str(data.get("FromDate",  "2025-08-04"))
            to_date    = str(data.get("ToDate",    "2025-08-08"))
            comments   = str(data.get("Comment",   "Automated test leave request"))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            leave_type = "Annual Leave"
            from_date  = "2025-08-04"
            to_date    = "2025-08-08"
            comments   = "Automated test leave request"

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Navigate to Leave > Apply"):
            leave_page = LeaveApplyPage(page)
            leave_page.navigate_to_apply_leave()

        with allure.step(f"Apply for {leave_type} from {from_date} to {to_date}"):
            leave_page.apply_leave(leave_type, from_date, to_date, comments)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify success message is displayed"):
            try:
                assert leave_page.is_success_shown(), "Success toast not visible after submission"
                result("passed",
                       "Leave application should be submitted successfully",
                       "Success toast is visible — leave request submitted")
            except Exception as exc:
                result("failed",
                       "Leave application should be submitted successfully",
                       f"Success toast not visible: {exc}")
                raise

        with allure.step("Navigate to My Leave and verify request appears"):
            try:
                my_leave = MyLeavePage(page)
                my_leave.navigate_to_my_leave()
                found = my_leave.find_leave_request(leave_type, from_date, to_date)
                assert found, f"Leave request not found: {leave_type} {from_date}–{to_date}"
                result("passed",
                       "Leave request should appear in My Leave list",
                       f"Leave request found: {leave_type} {from_date}–{to_date}")
            except Exception as exc:
                result("failed",
                       "Leave request should appear in My Leave list",
                       f"Request not found: {exc}")
                raise

        with allure.step("Verify leave status is Pending"):
            try:
                status = my_leave.get_leave_status(leave_type, from_date)
                assert status and "Pending" in status, \
                    f"Expected 'Pending Approval', got '{status}'"
                result("passed",
                       "Leave status should be Pending Approval",
                       f"Status is '{status}'")
            except Exception as exc:
                result("failed",
                       "Leave status should be Pending Approval",
                       f"Status check failed: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-LEAVE-008: Negative — invalid date range (From > To)
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Apply for Leave — Validation")
    @allure.title("TC-LEAVE-008: Invalid date range (From > To) should be rejected")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.boundary
    def test_apply_leave_invalid_date_range(self, page):
        """
        Verifies that a leave request with From Date > To Date is rejected
        with a validation error message.

        Test Data: testData/API_testData.xlsx → Web_UI → TC_Leave_InvalidDate
        Expected:  Form not submitted, validation error displayed.
        """

        # ── Arrange: read test data from Excel, fall back to defaults ─────────
        try:
            data       = read_api_data_from_excel("Web_UI", "TC_Leave_InvalidDate")
            leave_type = str(data.get("LeaveType", "Annual Leave"))
            from_date  = str(data.get("FromDate",  "2025-08-10"))
            to_date    = str(data.get("ToDate",    "2025-08-05"))  # before from_date
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            leave_type = "Annual Leave"
            from_date  = "2025-08-10"
            to_date    = "2025-08-05"

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Navigate to Leave > Apply"):
            leave_page = LeaveApplyPage(page)
            leave_page.navigate_to_apply_leave()

        with allure.step(f"Enter invalid date range: {from_date} to {to_date}"):
            leave_page.select_leave_type(leave_type)
            leave_page.enter_from_date(from_date)
            leave_page.enter_to_date(to_date)
            page.click(LeaveApplyLocator.APPLY_BUTTON)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify validation error is displayed"):
            try:
                assert leave_page.is_validation_error_shown(), \
                    "Validation error should be shown for invalid date range"
                result("passed",
                       "System should reject invalid date range with validation error",
                       "Validation error message is displayed")
            except Exception as exc:
                result("failed",
                       "System should reject invalid date range with validation error",
                       f"Validation error not shown: {exc}")
                raise

    # ─────────────────────────────────────────────────────────────────────────
    # TC-LEAVE-009: Negative — missing mandatory fields
    # ─────────────────────────────────────────────────────────────────────────

    @allure.story("Apply for Leave — Validation")
    @allure.title("TC-LEAVE-009: Submitting without mandatory fields should show validation errors")
    @allure.severity(allure.severity_level.NORMAL)
    def test_apply_leave_missing_mandatory_fields(self, page):
        """
        Verifies that submitting the leave form without required fields
        displays appropriate validation error messages.

        Test Data: No Excel data needed — form is submitted empty.
        Expected:  Validation errors shown for missing Leave Type, From Date, To Date.
        """

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Navigate to Leave > Apply"):
            leave_page = LeaveApplyPage(page)
            leave_page.navigate_to_apply_leave()

        with allure.step("Click Apply without filling any fields"):
            page.click(LeaveApplyLocator.APPLY_BUTTON)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify validation errors are displayed"):
            try:
                assert leave_page.is_validation_error_shown(), \
                    "Validation errors should be shown when mandatory fields are empty"
                result("passed",
                       "Validation errors should appear for missing mandatory fields",
                       "Validation error messages are displayed")
            except Exception as exc:
                result("failed",
                       "Validation errors should appear for missing mandatory fields",
                       f"Validation errors not shown: {exc}")
                raise
