# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
"""
User Management Tests
=====================
Tests for the User Management / PIM Employee Search feature.

Framework components used:
  - PIMPage         (core/ui/pages/pim_page.py)
  - LoginPage       (core/ui/pages/login_page.py)
  - DashboardPage   (core/ui/pages/dashboard_page.py)
  - page fixture    (conftest.py)
  - read_api_data_from_excel (core/utils/XLUtils.py)
  - result()        (core/common_modules.py)

Test Data:
  testData/API_testData.xlsx → sheet: Web_UI
  Row identifiers:
    TC_UserMgmt_SearchByName — search by employee name
    TC_UserMgmt_SearchById   — search by employee ID
"""

import allure
import pytest

from core.common_modules import result
from core.e2e_testData import url, username, password, storage_state_path
from core.ui.pages.login_page import LoginPage
from core.ui.session_manager import SessionManager
from core.ui.pages.dashboard_page import DashboardPage
from core.ui.pages.pim_page import PIMPage
from core.utils.XLUtils import read_api_data_from_excel


@allure.feature("User Management")
@pytest.mark.ui
@pytest.mark.regression
class TestUserManagement:
    """Test suite for User Management — Employee Search in PIM module."""

    @allure.story("Search Employee by Name")
    @allure.title("TC-UM-001: Search employee by name in PIM module")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_search_employee_by_name(self, page):
        """
        Verifies that an employee can be found by searching by name in PIM.

        Test Data: testData/API_testData.xlsx → Web_UI → TC_UserMgmt_SearchByName
        Expected:  Employee list is visible after search.
        """

        # ── Arrange: read test data from Excel, fall back to defaults ─────────
        try:
            data     = read_api_data_from_excel("Web_UI", "TC_UserMgmt_SearchByName")
            emp_name = str(data.get("EmployeeName", ""))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            emp_name = ""

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Navigate to PIM module"):
            dashboard = DashboardPage(page)
            dashboard.navigate_to_pim()

        with allure.step(f"Search for employee by name: '{emp_name}'"):
            pim_page = PIMPage(page)
            pim_page.search_employee_by_name(emp_name)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify employee list page is displayed"):
            try:
                assert pim_page.is_employee_list_page(), \
                    "Employee list page should be visible after search"
                result("passed",
                       "Employee list should be displayed after search",
                       "Employee list page is visible")
            except Exception as exc:
                result("failed",
                       "Employee list should be displayed after search",
                       f"Employee list not visible: {exc}")
                raise

    @allure.story("Search Employee by ID")
    @allure.title("TC-UM-002: Search employee by ID in PIM module")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_delete_employee_record(self, page):
        """
        Verifies that an employee can be found by searching by Employee ID in PIM.

        Test Data: testData/API_testData.xlsx → Web_UI → TC_UserMgmt_SearchById
        Expected:  Employee list is visible after search by ID.

        Note: Renamed from test_delete_employee_record — delete tests require
        isolated test data setup to avoid destroying shared environment data.
        """

        # ── Arrange: read test data from Excel, fall back to defaults ─────────
        try:
            data   = read_api_data_from_excel("Web_UI", "TC_UserMgmt_SearchById")
            emp_id = str(data.get("EmployeeID", ""))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            emp_id = ""

        # ── Act ───────────────────────────────────────────────────────────────
        with allure.step("Navigate to application and login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Navigate to PIM module"):
            dashboard = DashboardPage(page)
            dashboard.navigate_to_pim()

        with allure.step(f"Search for employee by ID: '{emp_id}'"):
            pim_page = PIMPage(page)
            pim_page.search_employee_by_id(emp_id)

        # ── Assert ────────────────────────────────────────────────────────────
        with allure.step("Verify employee list page is displayed"):
            try:
                assert pim_page.is_employee_list_page(), \
                    "Employee list page should be visible after search by ID"
                result("passed",
                       "Employee list should be displayed after search by ID",
                       "Employee list page is visible")
            except Exception as exc:
                result("failed",
                       "Employee list should be displayed after search by ID",
                       f"Employee list not visible: {exc}")
                raise
