# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
"""
Happy Path E2E test for Leave Apply feature.
Framework components reused:
* LeaveApplyPage (POM) from core.ui.pages.leave_page
* MyLeavePage (POM) from core.ui.pages.leave_page
* XLUtils test data workbook (leave scenarios dataset)
* SessionManager for leave module test user roles
* Playwright browser instance via conftest page fixture
"""

import allure
import pytest

from core.common_modules import result
from core.e2e_testData import url, username, password, storage_state_path
from core.ui.pages.leave_page import LeaveApplyPage, MyLeavePage
from core.ui.pages.login_page import LoginPage
from core.ui.pages.dashboard_page import DashboardPage
from core.ui.session_manager import SessionManager
from core.utils.XLUtils import read_api_data_from_excel


@allure.feature("Happy Path E2E")
class TestLeaveApplyFeature:

    @allure.story("Happy Path — Full Leave Application E2E")
    @allure.title("Happy Path: Apply for Leave and verify in My Leave")
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.ui
    def test_happy_path_apply_leave(self, page):
        """
        Happy path E2E: navigate to Leave > Apply, submit a leave request,
        verify it appears in My Leave with Pending Approval status.
        """
        with allure.step("Arrange: Load test data"):
            try:
                data = read_api_data_from_excel("LeaveApply", "KS-001")
                leave_type = str(data.get("leave_type", "Annual Leave"))
                from_date  = str(data.get("from_date",  "2025-09-01"))
                to_date    = str(data.get("to_date",    "2025-09-02"))
                comment    = str(data.get("comment",    "E2E test leave"))
            except Exception:
                leave_type = "Annual Leave"
                from_date  = "2025-09-01"
                to_date    = "2025-09-02"
                comment    = "E2E test leave"

        with allure.step("Arrange: Initialise page objects"):
            login_page      = LoginPage(page)
            dashboard_page  = DashboardPage(page)
            leave_apply_page = LeaveApplyPage(page)
            my_leave_page   = MyLeavePage(page)

        with allure.step("Act: Login"):
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)

        with allure.step("Act: Navigate to Leave > Apply"):
            dashboard_page.navigate_to_leave()
            leave_apply_page.navigate_to_apply_leave()

        with allure.step("Act: Fill and submit leave form"):
            leave_apply_page.apply_leave(leave_type, from_date, to_date, comment)

        with allure.step("Assert: Verify success"):
            try:
                assert leave_apply_page.is_success_shown(), \
                    "Leave application success indicator not shown"
                result("passed",
                       "Leave application submitted successfully",
                       "Success indicator displayed")
            except AssertionError as exc:
                result("failed",
                       "Leave application submitted successfully",
                       str(exc))
                raise

        with allure.step("Assert: Verify leave appears in My Leave"):
            dashboard_page.navigate_to_leave()
            my_leave_page.navigate_to_my_leave()
            found = my_leave_page.find_leave_request(leave_type, from_date, to_date)
            try:
                assert found, \
                    f"Leave record for '{leave_type}' ({from_date}–{to_date}) not found"
                result("passed",
                       "Leave record visible in My Leave",
                       "Leave record found in My Leave list")
            except AssertionError as exc:
                result("failed",
                       "Leave record visible in My Leave",
                       str(exc))
                raise
