# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY
"""
Employee Search Feature — Automated Test Suite
===============================================
User Story : HRM-202 — Search Employee
Feature    : PIM → Employee List → Search (OrangeHRM)

Framework components reused:
  - PIMPage     (core/ui/pages/pim_page.py)
  - LoginPage   (core/ui/pages/login_page.py)
  - page fixture (conftest.py)
  - read_api_data_from_excel (core/utils/XLUtils.py)
  - result()    (core/common_modules.py)

Test Data:
  testData/API_testData.xlsx → sheet: Web_UI
  Row identifiers:
    TC_PIM_SearchByName   — search by full name
    TC_PIM_SearchById     — search by employee ID
    TC_PIM_SearchNoResult — search with no results
"""

import allure
import pytest

from core.common_modules import result
from core.e2e_testData import url, username, password, storage_state_path
from core.ui.pages.login_page import LoginPage
from core.ui.session_manager import SessionManager
from core.ui.pages.pim_page import PIMPage
from core.utils.XLUtils import read_api_data_from_excel, read_cloud_env


def _login_and_navigate_to_pim(page) -> PIMPage:
    """Navigate to app. Handles session expiry automatically. Returns PIMPage."""
    login_page = LoginPage(page)
    page.goto(url, wait_until="domcontentloaded")
    SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
    login_page.verify_dashboard()
    pim_page = PIMPage(page)
    pim_page.navigate_to_pim()
    return pim_page


@allure.feature("Employee Search")
class TestEmployeeSearch:
    """End-to-end test suite for PIM → Employee List → Search (HRM-202)."""

    @allure.story("PIM Navigation")
    @allure.title("TC-SRCH-010: Navigate to PIM module — Employee List page is visible")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_navigate_to_pim_employee_list(self, page):
        """Navigate to PIM and verify Employee List is visible.
        Test Data: No Excel data needed.
        """
        cloud_env = read_cloud_env()
        with allure.step("Navigate to application and login"):
            login_page = LoginPage(page)
            page.goto(url, wait_until="domcontentloaded")
            SessionManager.ensure_authenticated(page, url, username, password, storage_state_path)
        with allure.step("Verify dashboard is visible"):
            try:
                login_page.verify_dashboard()
                result("passed", "Dashboard should be visible", "Dashboard is visible")
            except Exception as exc:
                result("failed", "Dashboard should be visible", f"NOT visible: {exc}")
                raise
        pim_page = PIMPage(page)
        with allure.step("Navigate to PIM"):
            pim_page.navigate_to_pim()
        with allure.step("Verify PIM Employee List is visible"):
            try:
                pim_page.verify_employee_list_page()
                result("passed", "Employee List should be visible", "Employee List is visible")
            except Exception as exc:
                result("failed", "Employee List should be visible", f"NOT visible: {exc}")
                raise

    @allure.story("Search by Name")
    @allure.title("TC-SRCH-001: Search employee by full name — matching results returned")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_search_employee_by_full_name(self, page):
        """Search by full name and verify results.
        Test Data: testData/API_testData.xlsx → Web_UI → TC_PIM_SearchByName
        """
        cloud_env = read_cloud_env()
        try:
            data          = read_api_data_from_excel("Web_UI", "TC_PIM_SearchByName")
            employee_name = str(data.get("EmployeeName", "man"))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            employee_name = "man"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search by name: '{employee_name}'"):
            try:
                pim_page.search_employee_by_name(employee_name)
                result("passed", "Search submitted", f"Searched for: '{employee_name}'")
            except Exception as exc:
                result("failed", "Search submitted", f"Error: {exc}")
                raise
        with allure.step("Verify results are displayed"):
            try:
                pim_page.verify_employee_in_list()
                result("passed", "Results should be visible", f"{pim_page.get_employee_row_count()} row(s)")
            except Exception as exc:
                result("failed", "Results should be visible", f"No results: {exc}")
                raise

    @allure.story("Search by Employee ID")
    @allure.title("TC-SRCH-002: Search employee by Employee ID — exact match returned")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_search_employee_by_id(self, page):
        """Search by Employee ID and verify results.
        Test Data: testData/API_testData.xlsx → Web_UI → TC_PIM_SearchById
        """
        cloud_env = read_cloud_env()
        try:
            data        = read_api_data_from_excel("Web_UI", "TC_PIM_SearchById")
            employee_id = str(data.get("EmployeeID", "0001"))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            employee_id = "0001"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search by Employee ID: '{employee_id}'"):
            try:
                pim_page.search_employee_by_id(employee_id)
                result("passed", "Search submitted", f"Searched for ID: '{employee_id}'")
            except Exception as exc:
                result("failed", "Search submitted", f"Error: {exc}")
                raise
        with allure.step("Verify results are displayed"):
            try:
                pim_page.verify_employee_in_list()
                result("passed", "Results should be visible", f"{pim_page.get_employee_row_count()} row(s)")
            except Exception as exc:
                result("failed", "Results should be visible", f"No results: {exc}")
                raise

    @allure.story("Search — No Results")
    @allure.title("TC-SRCH-003: Search with non-existent employee name — No Records Found")
    @allure.severity(allure.severity_level.NORMAL)
    def test_search_nonexistent_employee_name(self, page):
        """Search with non-existent name and verify No Records Found.
        Test Data: testData/API_testData.xlsx → Web_UI → TC_PIM_SearchNoResult
        """
        cloud_env = read_cloud_env()
        try:
            data             = read_api_data_from_excel("Web_UI", "TC_PIM_SearchNoResult")
            nonexistent_name = str(data.get("EmployeeName", "ZZZNONEXISTENTEMPLOYEE999"))
        except Exception as exc:
            print(f"  [TestData] Excel row not found — using defaults. ({exc})")
            nonexistent_name = "ZZZNONEXISTENTEMPLOYEE999"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search for non-existent name: '{nonexistent_name}'"):
            try:
                pim_page.search_employee_by_name(nonexistent_name)
                result("passed", "Search submitted", f"Searched for: '{nonexistent_name}'")
            except Exception as exc:
                result("failed", "Search submitted", f"Error: {exc}")
                raise
        with allure.step("Verify 'No Records Found' is displayed"):
            try:
                pim_page.verify_no_records_found()
                result("passed", "'No Records Found' should be visible", "'No Records Found' is visible")
            except Exception as exc:
                result("failed", "'No Records Found' should be visible", f"NOT visible: {exc}")
                raise

    @allure.story("Search — No Results")
    @allure.title("TC-SRCH-004: Search with non-existent Employee ID — No Records Found")
    @allure.severity(allure.severity_level.NORMAL)
    def test_search_nonexistent_employee_id(self, page):
        """Search with non-existent Employee ID and verify No Records Found.
        Test Data: No Excel row — uses hardcoded non-existent ID.
        """
        cloud_env    = read_cloud_env()
        nonexistent_id = "99999999"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search for non-existent Employee ID: '{nonexistent_id}'"):
            try:
                pim_page.search_employee_by_id(nonexistent_id)
                result("passed", "Search submitted", f"Searched for ID: '{nonexistent_id}'")
            except Exception as exc:
                result("failed", "Search submitted", f"Error: {exc}")
                raise
        with allure.step("Verify 'No Records Found' is displayed"):
            try:
                pim_page.verify_no_records_found()
                result("passed", "'No Records Found' should be visible", "'No Records Found' is visible")
            except Exception as exc:
                result("failed", "'No Records Found' should be visible", f"NOT visible: {exc}")
                raise

    @allure.story("Search Reset")
    @allure.title("TC-SRCH-005: Reset search filters — Employee List reloads all employees")
    @allure.severity(allure.severity_level.NORMAL)
    def test_reset_search_filters(self, page):
        """Search then reset and verify Employee List reloads.
        Test Data: No Excel data needed.
        """
        cloud_env   = read_cloud_env()
        search_name = "Admin"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search for: '{search_name}'"):
            pim_page.search_employee_by_name(search_name)
        with allure.step("Click Reset"):
            try:
                from core.ui.locators.pim_locator import PIMLocator
                pim_page.click(PIMLocator.RESET_BUTTON)
                pim_page.page.wait_for_load_state("domcontentloaded")
                result("passed", "Reset should clear filters", "Reset clicked")
            except Exception as exc:
                result("failed", "Reset should clear filters", f"Error: {exc}")
                raise
        with allure.step("Verify Employee List is reloaded"):
            try:
                pim_page.verify_employee_list_page()
                result("passed", "Employee List should reload after Reset", "Employee List visible")
            except Exception as exc:
                result("failed", "Employee List should reload after Reset", f"NOT visible: {exc}")
                raise

    @allure.story("Search — Default State")
    @allure.title("TC-SRCH-006: Empty search with no filters — all employees displayed")
    @allure.severity(allure.severity_level.NORMAL)
    def test_empty_search_returns_all_employees(self, page):
        """Click Search with no filters and verify all employees are shown.
        Test Data: No Excel data needed.
        """
        cloud_env = read_cloud_env()

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step("Click Search with no filters"):
            try:
                from core.ui.locators.pim_locator import PIMLocator
                pim_page.click(PIMLocator.SEARCH_BUTTON)
                pim_page.page.wait_for_load_state("domcontentloaded")
                result("passed", "Search submitted with no filters", "Search clicked")
            except Exception as exc:
                result("failed", "Search submitted with no filters", f"Error: {exc}")
                raise
        with allure.step("Verify at least one employee row is visible"):
            try:
                pim_page.verify_employee_in_list()
                result("passed", "Employees should be visible", f"{pim_page.get_employee_row_count()} row(s)")
            except Exception as exc:
                result("failed", "Employees should be visible", f"No rows: {exc}")
                raise

    @allure.story("Search by Name")
    @allure.title("TC-SRCH-007: Search employee by partial name — matching results returned")
    @allure.severity(allure.severity_level.NORMAL)
    def test_search_employee_by_partial_name(self, page):
        """Search by partial name and verify results.
        Test Data: No Excel data needed — uses hardcoded partial name.
        """
        cloud_env    = read_cloud_env()
        partial_name = "man"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Search by partial name: '{partial_name}'"):
            try:
                pim_page.search_employee_by_name(partial_name)
                result("passed", "Partial name search submitted", f"Searched for: '{partial_name}'")
            except Exception as exc:
                result("failed", "Partial name search submitted", f"Error: {exc}")
                raise
        with allure.step("Verify results are displayed"):
            try:
                pim_page.verify_employee_in_list()
                result("passed", "Results should be visible", f"{pim_page.get_employee_row_count()} row(s)")
            except Exception as exc:
                result("failed", "Results should be visible", f"No results: {exc}")
                raise

    @allure.story("Security Testing")
    @allure.title("TC-SRCH-008: Search with SQL injection payload — handled safely")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_search_sql_injection_in_name(self, page):
        """Enter SQL injection in search and verify no SQL error is exposed.
        Test Data: No Excel data needed — uses hardcoded SQL injection payload.
        """
        cloud_env   = read_cloud_env()
        sql_payload = "' OR '1'='1"

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Enter SQL injection payload: '{sql_payload}'"):
            try:
                pim_page.search_employee_by_name(sql_payload)
                result("passed", "SQL payload submitted without crash", "Search submitted")
            except Exception as exc:
                result("failed", "SQL payload submitted without crash", f"Error: {exc}")
                raise
        with allure.step("Verify no SQL error is exposed in page content"):
            try:
                content = page.content()
                sql_keywords = ["sql", "syntax error", "mysql", "postgresql",
                                "ora-", "sqlite", "database error"]
                exposed = any(kw in content.lower() for kw in sql_keywords)
                assert not exposed, "SQL error keywords found — possible SQL injection vulnerability!"
                result("passed", "No SQL error should be exposed", "No SQL error keywords found")
            except AssertionError as exc:
                result("failed", "No SQL error should be exposed", f"SECURITY RISK: {exc}")
                raise

    @allure.story("Security Testing")
    @allure.title("TC-SRCH-009: Search with XSS payload in name field — input sanitized")
    @allure.severity(allure.severity_level.CRITICAL)
    def test_search_xss_payload_in_name(self, page):
        """Enter XSS payload in search and verify no script execution.
        Test Data: No Excel data needed — uses hardcoded XSS payload.
        """
        cloud_env   = read_cloud_env()
        xss_payload = "<script>alert('xss')</script>"

        alert_triggered = {"value": False}
        page.on("dialog", lambda d: (setattr(alert_triggered, "value", True) or d.dismiss()))

        with allure.step("Login and navigate to PIM"):
            pim_page = _login_and_navigate_to_pim(page)
        with allure.step(f"Enter XSS payload: '{xss_payload}'"):
            try:
                pim_page.search_employee_by_name(xss_payload)
                result("passed", "XSS payload submitted without crash", "Search submitted")
            except Exception as exc:
                result("failed", "XSS payload submitted without crash", f"Error: {exc}")
                raise
        with allure.step("Verify no JavaScript alert was triggered"):
            try:
                assert not alert_triggered["value"], "XSS alert triggered — input NOT sanitized!"
                result("passed", "No alert should be triggered", "No alert triggered")
            except AssertionError as exc:
                result("failed", "No alert should be triggered", f"SECURITY RISK: {exc}")
                raise
        with allure.step("Verify no unescaped script tags in page content"):
            try:
                assert xss_payload not in page.content(), "Unescaped XSS tag found in page!"
                result("passed", "No unescaped script tags", "Page content is safe")
            except AssertionError as exc:
                result("failed", "No unescaped script tags", f"XSS tag found: {exc}")
                raise
