"""
AI QA Orchestrator — Full Agile Pipeline Workflow
==================================================
Implements the complete 22-stage Agile QA lifecycle:

  Jira/User Story
      ↓ [1]  Requirement Understanding      (StoryAnalyzer)
      ↓ [2]  Acceptance Criteria Analysis   (StoryAnalyzer — section 3)
      ↓ [3]  Requirement Ambiguity Detection (AmbiguityAnalyzer) ← GATE
      ↓ [4]  Impact Analysis                (ImpactAnalyzer)
      ↓ [5]  Risk Analysis                  (DefectPredictionAgent)
      ↓ [6]  Test Strategy / Key Scenarios  (KeyScenarioAgent)
      ↓ [7]  Test Case Generation           (TestGenerator)
      ↓ [8]  Test Case Review               (ReviewAgent) ← GATE
      ↓ [9]  Automation Feasibility         (AutomationRecommendationAgent)
      ↓ [10] Framework Reuse Analysis       (FrameworkReuseAgent)
      ↓ [11] Automation Code Generation     (AutomationAgent)
      ↓ [12] Automation Code Review         (AutomationReviewAgent) ← GATE + RETRY
      ↓ [13] Test Data Generation           (DataAgent)
      ↓ [14] RTM Generation                 (RTMAgent)
      ↓ [15] RTM Compliance Validation      (DecisionEngine) ← GATE
      ↓ [16] Pytest Execution               (subprocess — optional)
      ↓ [17] Failure Analysis               (TestReportAnalyzerAgent — optional)
      ↓ [18] Defect Classification          (DefectClassifierAgent — optional)
      ↓ [19] RTM Update                     (PipelineStateManager)
      ↓ [20] AI Dashboard                   (AIDashboardAgent)
      ↓ [21] Sprint QA Summary              (SprintSummaryAgent)
      ↓ [22] Retrospective Insights         (RetrospectiveAgent)

Architectural Principles:
  AI DECIDES / RECOMMENDS — agents produce outputs
  CODE VALIDATES — DecisionEngine applies deterministic rules
  FRAMEWORK EXECUTES — pytest runs the actual tests
  HUMAN APPROVES CRITICAL DECISIONS — ambiguity gate, release decision
  RTM PROVIDES TRACEABILITY — every artifact linked to requirements

Usage:
    from ai_orchestrator.orchestrator.workflow import AgileQAWorkflow

    workflow = AgileQAWorkflow()
    context = workflow.run(
        requirement="User Story: ...",
        jira_story_id="HRM-202",
        force_rerun=False,
        run_tests=False,       # set True to execute pytest after generation
        pause_on_ambiguity=True,  # set False to proceed despite ambiguities
    )
    print(context.sprint_summary)
"""

import os
import re
import time
from pathlib import Path
from typing import Optional

# ── Core framework imports ────────────────────────────────────────────────────
from ai_orchestrator.llm_factory import get_llm
from ai_orchestrator.llm.gateway import LLMGateway
from ai_orchestrator.pipeline_state_manager import PipelineStateManager
from ai_orchestrator.schemas.pipeline_schemas import PipelineContext
from ai_orchestrator.orchestrator.decision_engine import DecisionEngine

# ── All agents (native implementations) ──────────────────────────────────────
from ai_orchestrator.agents.requirement_analyzer_agent import StoryAnalyzer
from ai_orchestrator.agents.key_scenario_agent import KeyScenarioAgent
from ai_orchestrator.agents.test_case_generator_agent import Generator
from ai_orchestrator.agents.test_case_review_agent import ReviewAgent
from ai_orchestrator.agents.automation_recommendation_agent import AutomationRecommendationAgent
from ai_orchestrator.agents.automation_code_generator_agent import AutomationAgent
from ai_orchestrator.agents.test_data_generator_agent import DataAgent
from ai_orchestrator.agents.defect_prediction_agent import DefectPredictionAgent
from ai_orchestrator.agents.rtm_generator_agent import RTMAgent
from ai_orchestrator.agents.test_report_analyzer_agent import TestReportAnalyzerAgent
from ai_orchestrator.agents.ambiguity_detection_agent import AmbiguityAnalyzer
from ai_orchestrator.agents.impact_analysis_agent import ImpactAnalyzer
from ai_orchestrator.agents.framework_reuse_agent import FrameworkReuseAgent
from ai_orchestrator.agents.automation_review_agent import AutomationReviewAgent
from ai_orchestrator.agents.defect_classifier_agent import DefectClassifierAgent
from ai_orchestrator.agents.sprint_summary_agent import SprintSummaryAgent
from ai_orchestrator.agents.retrospective_agent import RetrospectiveAgent

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


# ─────────────────────────────────────────────────────────────────────────────
# Script saving helpers (reused from v1 orchestrator)
# ─────────────────────────────────────────────────────────────────────────────

_AI_GENERATED_MARKER = "# AUTO-GENERATED BY AI QA ORCHESTRATOR — DO NOT EDIT MANUALLY"


def _derive_script_filename(script_content: str, req_hash: str) -> str:
    code_start = 0
    import_match = re.search(r'^(?:import |from )', script_content, re.MULTILINE)
    if import_match:
        code_start = import_match.start()
    code_section = script_content[code_start:]

    feature_match = re.search(r'@allure\.feature\(["\']([^"\']+)["\']\)', code_section)
    if feature_match:
        feature = feature_match.group(1).strip()
        slug = re.sub(r'[^a-zA-Z0-9]+', '_', feature).strip('_').lower()
        return f"tests/ui/test_{slug}.py"

    class_match = re.search(r'class\s+(Test\w+)', code_section)
    if class_match:
        class_name = class_match.group(1)
        slug = re.sub(r'(?<!^)(?=[A-Z])', '_', class_name).lower()
        return f"tests/ui/{slug}.py"

    return f"tests/ui/test_ai_generated_{req_hash}.py"


def _save_script_to_file(script_content: str, req_hash: str) -> list:
    saved_paths = []
    target_rel = _derive_script_filename(script_content, req_hash)
    target_path = _PROJECT_ROOT / target_rel

    code = script_content
    fence_match = re.search(r'```(?:python)?\s*\n([\s\S]+?)```', script_content)
    if fence_match:
        code = fence_match.group(1)
    else:
        import_match = re.search(r'^(?:import |from )', script_content, re.MULTILINE)
        if import_match:
            code = script_content[import_match.start():]

    code = code.strip()
    if not code:
        print("  [AutomationAgent] ⚠️  No Python code found — skipping file save.")
        return saved_paths

    code = f"{_AI_GENERATED_MARKER}\n{code}"
    target_path.parent.mkdir(parents=True, exist_ok=True)

    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if _AI_GENERATED_MARKER not in existing:
            stem = target_path.stem
            safe_rel = str(target_rel).replace(
                target_path.name, f"{stem}_ai_{req_hash[:8]}.py"
            )
            target_path = _PROJECT_ROOT / safe_rel
            target_rel = safe_rel
            print(f"  [AutomationAgent] ⚠️  Hand-written file detected — saving to: {target_rel}")
        else:
            print(f"  [AutomationAgent] ♻️  Overwriting previous AI script: {target_rel}")
    else:
        print(f"  [AutomationAgent] 📝 Writing new AI script: {target_rel}")

    target_path.write_text(code, encoding="utf-8")
    print(f"  [AutomationAgent] ✅ Script saved → {target_path}")
    saved_paths.append(str(target_path))
    return saved_paths


# ─────────────────────────────────────────────────────────────────────────────
# AgileQAWorkflow
# ─────────────────────────────────────────────────────────────────────────────

class AgileQAWorkflow:
    """
    Full 22-stage Agile QA pipeline.

    Simulates the workflow of a QA Lead + Automation Lead + Senior SDET
    + Test Architect following an Agile/Scrum software testing process.

    Parameters
    ----------
    max_retries : int
        LLM gateway retry count (default: 3).
    timeout_seconds : int
        LLM call timeout in seconds (default: 120).
    """

    def __init__(
        self,
        max_retries: int = 3,
        timeout_seconds: int = 120,
    ) -> None:
        self._max_retries = max_retries
        self._timeout_seconds = timeout_seconds
        self._engine = DecisionEngine()

    # ─────────────────────────────────────────────────────────────────────────
    # Public entry point
    # ─────────────────────────────────────────────────────────────────────────

    def run(
        self,
        requirement: str,
        jira_story_id: str = "",
        force_rerun: bool = False,
        run_tests: bool = False,
        pause_on_ambiguity: bool = True,
    ) -> PipelineContext:
        """
        Execute the full Agile QA pipeline.

        Parameters
        ----------
        requirement : str
            Raw requirement text (Jira story, BRD excerpt, acceptance criteria).
        jira_story_id : str
            Optional Jira story ID for traceability (e.g. "HRM-202").
        force_rerun : bool
            If True, bypass all caches and re-run all agents.
        run_tests : bool
            If True, execute pytest after code generation and analyze results.
        pause_on_ambiguity : bool
            If True (default), pause pipeline when ambiguities are found.
            If False, proceed despite ambiguities (useful for CI/CD).

        Returns
        -------
        PipelineContext
            Complete pipeline context with all agent outputs and decisions.
        """
        total_start = time.time()

        # ── Initialize context and state ──────────────────────────────────────
        ctx = PipelineContext(
            requirement=requirement,
            jira_story_id=jira_story_id,
        )

        state = PipelineStateManager(force=force_rerun)
        state.print_state_summary()

        # ── Initialize LLM with gateway ───────────────────────────────────────
        try:
            raw_llm = get_llm()
            llm = LLMGateway(
                raw_llm,
                max_retries=self._max_retries,
                timeout_seconds=self._timeout_seconds,
                fallback_on_failure=True,
            )
        except Exception as exc:
            print(f"\n[ERROR] Failed to initialize LLM: {exc}")
            print("[INFO] Pipeline will run in degraded mode (no LLM calls).")
            llm = None  # type: ignore[assignment]

        # ── Register requirement ──────────────────────────────────────────────
        ctx.req_hash = state.register_requirement(requirement)

        self._print_header(ctx)

        # ── Run all pipeline stages ───────────────────────────────────────────
        if llm is None:
            ctx.add_error("init", "LLM unavailable — pipeline cannot run agent stages.")
            return ctx

        # Instantiate all agents
        agents = self._build_agents(llm)

        # Execute stages
        self._stage_1_requirement_analysis(ctx, state, agents)
        self._stage_2_ambiguity_detection(ctx, state, agents, pause_on_ambiguity)

        if ctx.pipeline_stage == "PAUSED_AMBIGUITY":
            self._print_pause_notice(ctx)
            return ctx

        self._stage_3_impact_analysis(ctx, state, agents)
        self._stage_4_risk_analysis(ctx, state, agents)
        self._stage_5_key_scenarios(ctx, state, agents)
        self._stage_6_test_cases(ctx, state, agents)
        self._stage_7_test_review(ctx, state, agents)
        self._stage_8_automation_recommendation(ctx, state, agents)
        self._stage_9_framework_reuse(ctx, state, agents)
        self._stage_10_automation_generation(ctx, state, agents)
        self._stage_11_automation_review(ctx, state, agents)
        self._stage_12_test_data(ctx, state, agents)
        self._stage_13_rtm(ctx, state, agents)
        self._stage_14_rtm_validation(ctx)

        if run_tests:
            self._stage_15_pytest_execution(ctx)
            self._stage_16_failure_analysis(ctx, state, agents)
            self._stage_17_defect_classification(ctx, state, agents)

        self._stage_18_rtm_update(ctx, state)
        self._stage_19_sprint_summary(ctx, state, agents)
        self._stage_20_retrospective(ctx, state, agents)

        # ── Final summary ─────────────────────────────────────────────────────
        total_elapsed = time.time() - total_start
        self._print_final_summary(ctx, total_elapsed, llm)

        return ctx

    # ─────────────────────────────────────────────────────────────────────────
    # Agent factory
    # ─────────────────────────────────────────────────────────────────────────

    def _build_agents(self, llm) -> dict:
        """Instantiate all agents with the shared LLM gateway."""
        return {
            "story_analyzer":          StoryAnalyzer(llm),
            "ambiguity_analyzer":      AmbiguityAnalyzer(llm),
            "impact_analyzer":         ImpactAnalyzer(llm),
            "key_scenario":            KeyScenarioAgent(llm),
            "test_generator":          Generator(llm),
            "review":                  ReviewAgent(llm),
            "automation_recommender":  AutomationRecommendationAgent(llm),
            "framework_reuse":         FrameworkReuseAgent(llm),
            "automation":              AutomationAgent(llm),
            "automation_review":       AutomationReviewAgent(llm),
            "data":                    DataAgent(llm),
            "defect_prediction":       DefectPredictionAgent(llm),
            "rtm":                     RTMAgent(llm),
            "defect_classifier":       DefectClassifierAgent(llm),
            "sprint_summary":          SprintSummaryAgent(llm),
            "retrospective":           RetrospectiveAgent(llm),
        }

    # ─────────────────────────────────────────────────────────────────────────
    # Pipeline stages
    # ─────────────────────────────────────────────────────────────────────────

    def _stage_1_requirement_analysis(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[1/22] Requirement Understanding + Acceptance Criteria Analysis."""
        self._print_stage("[1/22] Requirement Analysis", "StoryAnalyzer")
        ctx.analysis = self._run_or_load(
            state, ctx.requirement, "analysis",
            lambda: agents["story_analyzer"].analyze(ctx.requirement),
        )
        ctx.mark_complete("analysis")

    def _stage_2_ambiguity_detection(
        self, ctx: PipelineContext, state: PipelineStateManager,
        agents: dict, pause_on_ambiguity: bool
    ) -> None:
        """[2/22] Requirement Ambiguity Detection — GATE."""
        self._print_stage("[2/22] Ambiguity Detection", "AmbiguityAnalyzer")
        ctx.ambiguity_report = self._run_or_load(
            state, ctx.requirement, "ambiguity",
            lambda: agents["ambiguity_analyzer"].analyze(ctx.requirement, ctx.analysis),
        )
        ctx.mark_complete("ambiguity")

        decision = self._engine.should_proceed_after_ambiguity(ctx)
        self._print_decision(decision)

        if not decision.proceed and pause_on_ambiguity:
            ctx.pipeline_stage = "PAUSED_AMBIGUITY"
            return

        if not decision.proceed:
            print("  [INFO] pause_on_ambiguity=False — proceeding despite ambiguities.")

    def _stage_3_impact_analysis(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[3/22] Impact Analysis."""
        self._print_stage("[3/22] Impact Analysis", "ImpactAnalyzer")
        ctx.impact_report = self._run_or_load(
            state, ctx.requirement, "impact",
            lambda: agents["impact_analyzer"].analyze(ctx.requirement, ctx.analysis),
        )
        ctx.mark_complete("impact")

    def _stage_4_risk_analysis(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[4/22] Risk Analysis (FMEA)."""
        self._print_stage("[4/22] Risk Analysis", "DefectPredictionAgent")
        ctx.defects = self._run_or_load(
            state, ctx.requirement, "defects",
            lambda: agents["defect_prediction"].predict(ctx.analysis, ""),
        )
        ctx.mark_complete("defects")

    def _stage_5_key_scenarios(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[5/22] Test Strategy + Key Scenario Generation."""
        self._print_stage("[5/22] Key Scenarios", "KeyScenarioAgent")
        ctx.key_scenarios = self._run_or_load(
            state, ctx.requirement, "key_scenarios",
            lambda: agents["key_scenario"].extract(ctx.requirement, ctx.analysis),
        )
        ctx.mark_complete("key_scenarios")

    def _stage_6_test_cases(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[6/22] Test Case Generation."""
        self._print_stage("[6/22] Test Case Generation", "TestGenerator")
        ctx.test_cases = self._run_or_load(
            state, ctx.requirement, "test_cases",
            lambda: agents["test_generator"].generate(ctx.analysis),
        )
        ctx.mark_complete("test_cases")

        # Validate test case count
        tc_decision = self._engine.validate_test_case_count(ctx)
        self._print_decision(tc_decision)

        # Register TC IDs in state
        tc_status = state.register_test_cases(ctx.requirement, ctx.test_cases)
        duplicates = [tc for tc, s in tc_status.items() if s == "DUPLICATE"]
        if duplicates:
            print(f"  ⚠️  DUPLICATE TEST CASES: {sorted(duplicates)}")

    def _stage_7_test_review(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[7/22] Test Case Review — GATE."""
        self._print_stage("[7/22] Test Case Review", "ReviewAgent")
        ctx.review = self._run_or_load(
            state, ctx.requirement, "review",
            lambda: agents["review"].review(ctx.analysis, ctx.test_cases),
        )
        ctx.mark_complete("review")

        decision = self._engine.should_proceed_after_review(ctx)
        self._print_decision(decision)

    def _stage_8_automation_recommendation(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[8/22] Automation Feasibility + Strategy."""
        self._print_stage("[8/22] Automation Recommendation", "AutomationRecommendationAgent")
        ctx.recommendation = self._run_or_load(
            state, ctx.requirement, "recommendation",
            lambda: agents["automation_recommender"].recommend(ctx.key_scenarios),
        )
        ctx.mark_complete("recommendation")

    def _stage_9_framework_reuse(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[9/22] Existing Framework Reuse Analysis."""
        self._print_stage("[9/22] Framework Reuse Analysis", "FrameworkReuseAgent")
        ctx.reuse_report = self._run_or_load(
            state, ctx.requirement, "reuse",
            lambda: agents["framework_reuse"].analyze(
                ctx.requirement, ctx.key_scenarios, ctx.recommendation
            ),
        )
        ctx.mark_complete("reuse")

    def _stage_10_automation_generation(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[10/22] Automation Code Generation."""
        self._print_stage("[10/22] Automation Code Generation", "AutomationAgent")

        scripts_cached = state.get_cached_output(ctx.requirement, "scripts")
        if scripts_cached:
            ctx.scripts = scripts_cached
            print("  ⚡ LOADED FROM CACHE")
            saved = _save_script_to_file(scripts_cached, ctx.req_hash)
            if saved:
                print(f"  📂 Script(s) restored from cache: {saved}")
        else:
            start = time.time()
            ctx.scripts = agents["automation"].generate_script(ctx.key_scenarios)
            elapsed = time.time() - start
            print(f"  ✅ Completed in {elapsed:.2f}s")
            state.save_agent_output(ctx.requirement, "scripts", ctx.scripts)

            saved = _save_script_to_file(ctx.scripts, ctx.req_hash)
            if saved:
                print(f"  📂 Script(s) written: {saved}")

            script_paths = re.findall(r'tests/(?:ui|api)/test_\w+\.py', ctx.scripts)
            for sp in script_paths:
                state.register_script(ctx.requirement, sp)

        ctx.mark_complete("scripts")

    def _stage_11_automation_review(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[11/22] Automation Code Review — GATE with retry."""
        self._print_stage("[11/22] Automation Code Review", "AutomationReviewAgent")

        retry_count = 0
        while True:
            cache_key = f"automation_review_{retry_count}"
            ctx.automation_review = self._run_or_load(
                state, ctx.requirement, cache_key,
                lambda: agents["automation_review"].review(
                    ctx.scripts, ctx.key_scenarios, ctx.reuse_report
                ),
            )
            ctx.mark_complete(f"automation_review_{retry_count}")

            decision = self._engine.should_proceed_after_automation_review(
                ctx, retry_count=retry_count
            )
            self._print_decision(decision)

            if decision.proceed:
                break

            # Retry: regenerate code with review feedback injected
            retry_count += 1
            print(f"\n  🔄 Retrying AutomationAgent with review feedback (attempt {retry_count})...")
            # Inject review feedback into the key_scenarios context for the retry
            feedback_context = (
                f"{ctx.key_scenarios}\n\n"
                f"=== PREVIOUS CODE REVIEW FEEDBACK (MUST FIX) ===\n"
                f"{ctx.automation_review}"
            )
            start = time.time()
            ctx.scripts = agents["automation"].generate_script(feedback_context)
            elapsed = time.time() - start
            print(f"  ✅ Regenerated in {elapsed:.2f}s")
            state.save_agent_output(ctx.requirement, f"scripts_retry_{retry_count}", ctx.scripts)
            saved = _save_script_to_file(ctx.scripts, ctx.req_hash)
            if saved:
                print(f"  📂 Revised script(s) written: {saved}")

    def _stage_12_test_data(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[12/22] Test Data Generation."""
        self._print_stage("[12/22] Test Data Generation", "DataAgent")
        ctx.test_data = self._run_or_load(
            state, ctx.requirement, "test_data",
            lambda: agents["data"].generate_data(ctx.key_scenarios),
        )
        ctx.mark_complete("test_data")

    def _stage_13_rtm(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[13/22] RTM Generation."""
        self._print_stage("[13/22] RTM Generation", "RTMAgent")
        ctx.rtm = self._run_or_load(
            state, ctx.requirement, "rtm",
            lambda: agents["rtm"].generate_rtm(
                requirement=ctx.requirement,
                analysis=ctx.analysis,
                test_cases=ctx.test_cases,
                key_scenarios=ctx.key_scenarios,
                review=ctx.review,
                recommendation=ctx.recommendation,
                defects=ctx.defects,
            ),
        )
        ctx.mark_complete("rtm")

        # Update persistent RTM store
        print("\n  Updating RTM store...")
        rtm_summary = state.update_rtm_store(ctx.requirement, ctx.rtm)
        added = len(rtm_summary.get("added", []))
        skipped = len(rtm_summary.get("skipped", []))
        print(f"  RTM Store: {added} entries ADDED, {skipped} SKIPPED")

    def _stage_14_rtm_validation(self, ctx: PipelineContext) -> None:
        """[14/22] RTM Compliance Validation."""
        self._print_stage("[14/22] RTM Compliance Validation", "DecisionEngine")
        decision = self._engine.validate_rtm_compliance(ctx)
        self._print_decision(decision)
        ctx.mark_complete("rtm_validation")

    def _stage_15_pytest_execution(self, ctx: PipelineContext) -> None:
        """[15/22] Pytest Execution (optional)."""
        self._print_stage("[15/22] Pytest Execution", "subprocess")
        import subprocess
        try:
            result = subprocess.run(
                ["python", "-m", "pytest", "tests/", "-v", "--tb=short",
                 "--no-header", "-q"],
                capture_output=True,
                text=True,
                cwd=str(_PROJECT_ROOT),
                timeout=300,
            )
            ctx.execution_results = result.stdout + result.stderr
            print(f"  pytest exit code: {result.returncode}")
            print(f"  Output preview: {ctx.execution_results[:300]}...")
        except subprocess.TimeoutExpired:
            ctx.execution_results = "[TIMEOUT] pytest execution exceeded 300 seconds."
            ctx.add_error("pytest", "Execution timeout")
        except Exception as exc:
            ctx.execution_results = f"[ERROR] pytest execution failed: {exc}"
            ctx.add_error("pytest", str(exc))
        ctx.mark_complete("execution")

    def _stage_16_failure_analysis(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[16/22] AI Failure Analysis (optional — runs if tests were executed)."""
        if not ctx.execution_results:
            ctx.mark_skipped("failure_analysis", "No execution results available")
            return

        self._print_stage("[16/22] Failure Analysis", "TestReportAnalyzerAgent")
        try:
            analyzer = TestReportAnalyzerAgent()
            results = analyzer.analyze()
            ctx.execution_results = str(results)
            ctx.mark_complete("failure_analysis")
        except Exception as exc:
            ctx.add_error("failure_analysis", str(exc))
            ctx.mark_skipped("failure_analysis", f"Error: {exc}")

    def _stage_17_defect_classification(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[17/22] Defect Classification (optional — runs if tests were executed)."""
        if not ctx.execution_results:
            ctx.mark_skipped("defect_classification", "No execution results available")
            return

        self._print_stage("[17/22] Defect Classification", "DefectClassifierAgent")
        try:
            import json
            results_dict = {}
            try:
                results_dict = json.loads(ctx.execution_results)
            except Exception:
                results_dict = {"raw": ctx.execution_results}

            ctx.defect_classification = self._run_or_load(
                state, ctx.requirement, "defect_classification",
                lambda: agents["defect_classifier"].classify(
                    results_dict, ctx.test_cases, ctx.rtm
                ),
            )
            ctx.mark_complete("defect_classification")
        except Exception as exc:
            ctx.add_error("defect_classification", str(exc))
            ctx.mark_skipped("defect_classification", f"Error: {exc}")

    def _stage_18_rtm_update(
        self, ctx: PipelineContext, state: PipelineStateManager
    ) -> None:
        """[18/22] RTM Update with execution results."""
        self._print_stage("[18/22] RTM Update", "PipelineStateManager")
        # RTM was already updated in stage 13; this stage handles post-execution updates
        coverage = state.get_rtm_coverage(ctx.requirement)
        if coverage:
            print(f"  RTM Coverage: {coverage.get('covered', 0)}/{coverage.get('total_requirements', 0)} requirements covered")
            print(f"  Automation  : {coverage.get('automated', 0)}/{coverage.get('total_test_cases', 0)} test cases automated")
        ctx.mark_complete("rtm_update")

    def _stage_19_sprint_summary(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[19/22] Sprint QA Summary."""
        self._print_stage("[19/22] Sprint QA Summary", "SprintSummaryAgent")
        ctx.sprint_summary = self._run_or_load(
            state, ctx.requirement, "sprint_summary",
            lambda: agents["sprint_summary"].summarize(
                requirement=ctx.requirement,
                analysis=ctx.analysis,
                ambiguity_report=ctx.ambiguity_report,
                impact_report=ctx.impact_report,
                test_cases=ctx.test_cases,
                review=ctx.review,
                recommendation=ctx.recommendation,
                reuse_report=ctx.reuse_report,
                defect_prediction=ctx.defects,
                rtm=ctx.rtm,
                execution_results=ctx.execution_results,
                defect_classification=ctx.defect_classification,
            ),
        )
        ctx.mark_complete("sprint_summary")

        # Extract release recommendation
        release_decision = self._engine.assess_release_readiness(ctx)
        self._print_decision(release_decision)

    def _stage_20_retrospective(
        self, ctx: PipelineContext, state: PipelineStateManager, agents: dict
    ) -> None:
        """[20/22] Retrospective Insights."""
        self._print_stage("[20/22] Retrospective Insights", "RetrospectiveAgent")
        ctx.retrospective = self._run_or_load(
            state, ctx.requirement, "retrospective",
            lambda: agents["retrospective"].generate_insights(
                sprint_summary=ctx.sprint_summary,
                ambiguity_report=ctx.ambiguity_report,
                review_verdict=ctx.review,
                automation_review=ctx.automation_review,
                defect_classification=ctx.defect_classification,
            ),
        )
        ctx.mark_complete("retrospective")

        state.print_state_summary()
        state.print_rtm_store_summary()

    # ─────────────────────────────────────────────────────────────────────────
    # Cache helper (reused from v1 orchestrator)
    # ─────────────────────────────────────────────────────────────────────────

    def _run_or_load(
        self,
        state: PipelineStateManager,
        requirement: str,
        agent_key: str,
        agent_fn,
    ) -> str:
        """Return cached output if available, otherwise call agent_fn() and cache."""
        cached = state.get_cached_output(requirement, agent_key)
        if cached:
            print(f"  ⚡ LOADED FROM CACHE [{agent_key}]")
            return cached

        start = time.time()
        output = agent_fn()
        elapsed = time.time() - start
        print(f"  ✅ Completed in {elapsed:.2f}s")
        state.save_agent_output(requirement, agent_key, output)
        return output

    # ─────────────────────────────────────────────────────────────────────────
    # Print helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _print_header(self, ctx: PipelineContext) -> None:
        print("\n" + "=" * 70)
        print("🚀 AI QA ORCHESTRATOR — FULL AGILE PIPELINE")
        print("=" * 70)
        print(f"  Requirement hash : {ctx.req_hash}")
        if ctx.jira_story_id:
            print(f"  Jira Story ID    : {ctx.jira_story_id}")
        print(f"  Requirement      : {ctx.requirement[:80].strip()}...")
        print("=" * 70)

    def _print_stage(self, stage_label: str, agent_name: str) -> None:
        print(f"\n{'─' * 70}")
        print(f"  {stage_label}  [{agent_name}]")
        print("─" * 70)

    def _print_decision(self, decision) -> None:
        icon = "✅" if decision.proceed else "🛑"
        print(f"  {icon} Decision: {decision.reason}")
        for warning in decision.warnings:
            print(f"  ⚠️  {warning}")
        if decision.action_required:
            print(f"  📋 Action required: {decision.action_required}")

    def _print_pause_notice(self, ctx: PipelineContext) -> None:
        print("\n" + "=" * 70)
        print("🛑 PIPELINE PAUSED — REQUIREMENT CLARIFICATION NEEDED")
        print("=" * 70)
        print("\nThe following questions must be answered before the pipeline")
        print("can proceed to test design:\n")
        questions = self._engine.extract_ambiguity_questions(ctx.ambiguity_report)
        for i, q in enumerate(questions, 1):
            print(f"  Q{i}. {q}")
        print("\nSee the full ambiguity report for details.")
        print("\nTo proceed despite ambiguities, run with pause_on_ambiguity=False")
        print("=" * 70)

    def _print_final_summary(
        self, ctx: PipelineContext, elapsed: float, llm
    ) -> None:
        print("\n" + "=" * 70)
        print(f"🏁 PIPELINE COMPLETE — Total Time: {elapsed:.2f}s")
        print("=" * 70)
        summary = ctx.summary()
        print(f"  Stages completed : {summary['stages_completed']}")
        print(f"  Stages skipped   : {summary['stages_skipped']}")
        print(f"  Errors           : {summary['errors']}")
        print(f"  Ambiguity status : {summary['ambiguity_status']}")
        print(f"  Review verdict   : {summary['review_verdict']}")
        print(f"  Auto verdict     : {summary['automation_verdict']}")
        print(f"  Release          : {summary['release_recommendation']}")
        if hasattr(llm, 'stats'):
            stats = llm.stats()
            print(f"\n  LLM calls        : {stats['call_count']}")
            print(f"  LLM total time   : {stats['total_duration_seconds']}s")
            print(f"  LLM avg time     : {stats['average_duration_seconds']}s/call")
        print("\n  Pipeline Artifacts:")
        print(f"    ✅ Requirement Analysis  — {ctx.req_hash}")
        print(f"    ✅ Ambiguity Report      — {summary['ambiguity_status']}")
        print(f"    ✅ Impact Analysis")
        print(f"    ✅ Test Cases")
        print(f"    ✅ Test Review           — {summary['review_verdict']}")
        print(f"    ✅ Automation Scripts    — saved to tests/")
        print(f"    ✅ Test Data             — testData/API_testData.xlsx")
        print(f"    ✅ Defect Predictions    — FMEA risk register")
        print(f"    ✅ RTM                   — rtm_store.xlsx")
        print(f"    ✅ Sprint Summary")
        print(f"    ✅ Retrospective Insights")
        print(f"\n  Release Recommendation: {summary['release_recommendation']}")
        print("=" * 70)
